-- Comandos sql para apagar tabelas do banco de dados --
-- Autor: Rodolfo Romaioli Ribeiro de Jesus - rodolfo.romaioli@gmail.com
-- Criado: 15/05/2018 11:30
-- Alterado em 01/04/2019 às 10:26

-- teste salvar--
-- DROP TABLE antranetsinan, antranet70, antranet, chikonnet, coquenet, dengnet, famarnet,
-- leptonet, exantnet, chiku_ial,coque_ial,dengue_ial,febrea_ial,zika_ial,sarampo_ial,resultado_ccz,resultado_ccz_lepto,resultado_esporo;

-- Comandos sql para atualizar banco de dados --
-- Autor: Rodolfo Romaioli Ribeiro de Jesus - rodolfo.romaioli@gmail.com
-- Criado: 15/05/2018 11:30
-- Alterado em 20/12/2012 às 10:26

-- Script criado para carregar tabelas extraídas de bancos de dados -> SinanNet, Getwin e GAL-Instituto Adolfo Lutz
--
-- Carregando


-- script anti-rabica --

-- Criando a tabela antranetsinan
CREATE TABLE `antranetsinan` (`NU_NOTIFIC` varchar(7) DEFAULT NULL, `TP_NOT` int(1) DEFAULT NULL, `ID_AGRAVO` varchar(3) DEFAULT NULL, `DT_NOTIFIC` varchar(10) DEFAULT NULL, `SEM_NOT` varchar(6) DEFAULT NULL, `NU_ANO` int(4) DEFAULT NULL, `SG_UF_NOT` int(2) DEFAULT NULL, `ID_MUNICIP` int(6) DEFAULT NULL, `ID_REGIONA` int(4) DEFAULT NULL, `ID_UNIDADE` int(7) DEFAULT NULL, `DT_SIN_PRI` varchar(10) DEFAULT NULL, `SEM_PRI` varchar(6) DEFAULT NULL, `NM_PACIENT` varchar(66) DEFAULT NULL, `DT_NASC` varchar(10) DEFAULT NULL, `FONETICA_N` varchar(21) DEFAULT NULL, `SOUNDEX` varchar(15) DEFAULT NULL, `NU_IDADE_N` int(4) DEFAULT NULL, `CS_SEXO` varchar(1) DEFAULT NULL, `CS_GESTANT` int(1) DEFAULT NULL, `CS_RACA` varchar(1) DEFAULT NULL, `CS_ESCOL_N` varchar(2) DEFAULT NULL, `ID_CNS_SUS` varchar(15) DEFAULT NULL, `NM_MAE_PAC` varchar(46) DEFAULT NULL, `SG_UF` int(2) DEFAULT NULL, `ID_MN_RESI` int(6) DEFAULT NULL, `ID_RG_RESI` varchar(4) DEFAULT NULL, `ID_DISTRIT` varchar(2) DEFAULT NULL, `ID_BAIRRO` varchar(2) DEFAULT NULL, `NM_BAIRRO` varchar(20) DEFAULT NULL, `ID_LOGRADO` varchar(6) DEFAULT NULL, `NM_LOGRADO` varchar(59) DEFAULT NULL, `NU_NUMERO` varchar(6) DEFAULT NULL, `NM_COMPLEM` varchar(30) DEFAULT NULL, `ID_GEO1` varchar(10) DEFAULT NULL, `ID_GEO2` varchar(10) DEFAULT NULL, `NM_REFEREN` varchar(34) DEFAULT NULL, `NU_CEP` varchar(8) DEFAULT NULL, `NU_DDD_TEL` varchar(2) DEFAULT NULL, `NU_TELEFON` varchar(9) DEFAULT NULL, `CS_ZONA` varchar(1) DEFAULT NULL, `ID_PAIS` int(1) DEFAULT NULL, `ID_OCUPA_N` varchar(6) DEFAULT NULL, `ANT_CONTAT` int(1) DEFAULT NULL, `ANT_ARRANH` int(1) DEFAULT NULL, `ANT_LAMBED` int(1) DEFAULT NULL, `ANT_MORDED` int(1) DEFAULT NULL, `ANT_OUTRO_` int(1) DEFAULT NULL, `ANT_MUCOSA` int(1) DEFAULT NULL, `ANT_CABECA` int(1) DEFAULT NULL, `ANT_MAOS` int(1) DEFAULT NULL, `ANT_TRONCO` int(1) DEFAULT NULL, `ANT_MEMBRO` int(1) DEFAULT NULL, `ANT_MEMB_1` int(1) DEFAULT NULL, `FERIMENTO` varchar(1) DEFAULT NULL, `ANT_PROFUN` varchar(1) DEFAULT NULL, `ANT_SUPERF` varchar(1) DEFAULT NULL, `ANT_DILACE` varchar(1) DEFAULT NULL, `ANT_DT_EXP` varchar(10) DEFAULT NULL, `PRE_EXPOS` varchar(1) DEFAULT NULL, `POS_EXPOS` varchar(1) DEFAULT NULL, `TRA_ANTIGO` varchar(1) DEFAULT NULL, `DOSES` varchar(1) DEFAULT NULL, `ANIMAL` int(1) DEFAULT NULL, `HERBIV_DES` varchar(10) DEFAULT NULL, `OUTRO_DES` varchar(16) DEFAULT NULL, `CONDIC_ANI` varchar(1) DEFAULT NULL, `OBSERVACAO` varchar(1) DEFAULT NULL, `TRAT_ATUAL` varchar(1) DEFAULT NULL, `LAB_VACINA` varchar(1) DEFAULT NULL, `LAB_VAC_DE` varchar(16) DEFAULT NULL, `LOTE_VAC` varchar(8) DEFAULT NULL, `DT_VENCIM` varchar(10) DEFAULT NULL, `DT_DOSE_1` varchar(5) DEFAULT NULL, `DT_DOSE_2` varchar(5) DEFAULT NULL, `DT_DOSE_3` varchar(5) DEFAULT NULL, `DT_DOSE_4` varchar(5) DEFAULT NULL, `DT_DOSE_5` varchar(10) DEFAULT NULL, `DT_VAC_1` varchar(10) DEFAULT NULL, `DT_VAC_2` varchar(10) DEFAULT NULL, `DT_VAC_3` varchar(10) DEFAULT NULL, `DT_VAC_4` varchar(10) DEFAULT NULL, `DT_VAC_5` varchar(10) DEFAULT NULL, `FIM_ANIMAL` varchar(1) DEFAULT NULL, `TRA_INTERR` varchar(1) DEFAULT NULL, `TRA_MOTIVO` varchar(1) DEFAULT NULL, `BUSCA_ATIV` varchar(1) DEFAULT NULL, `REACAO_VAC` varchar(1) DEFAULT NULL, `TRA_INDI_N` varchar(1) DEFAULT NULL, `TRA_PESO` varchar(3) DEFAULT NULL, `TRA_QTD_SO` varchar(3) DEFAULT NULL, `TIP_SORO` varchar(1) DEFAULT NULL, `TRA_INFILT` varchar(1) DEFAULT NULL, `TRA_INFI_1` varchar(1) DEFAULT NULL, `LAB_SORO` varchar(1) DEFAULT NULL, `LAB_SOR_DE` varchar(6) DEFAULT NULL, `TRA_NUM_PA` varchar(10) DEFAULT NULL, `REACAO_SOR` varchar(1) DEFAULT NULL, `DT_ENCERRA` varchar(10) DEFAULT NULL, `DT_DIGITA` varchar(10) DEFAULT NULL, `DT_TRANSUS` varchar(10) DEFAULT NULL, `DT_TRANSDM` varchar(10) DEFAULT NULL, `DT_TRANSSM` varchar(10) DEFAULT NULL, `DT_TRANSRM` varchar(10) DEFAULT NULL, `DT_TRANSRS` varchar(10) DEFAULT NULL, `DT_TRANSSE` varchar(10) DEFAULT NULL, `NU_LOTE_V` varchar(10) DEFAULT NULL, `NU_LOTE_H` varchar(10) DEFAULT NULL, `IDENT_MICR` bigint(13) DEFAULT NULL, `OBS` varchar(254) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Carregando os dados  do excel csv da pasta abaixo ...
LOAD DATA INFILE 'E:/csv/ANTRANET.csv'
INTO TABLE `antranetsinan` CHARACTER SET utf8 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `antranetsinan` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM antranetsinan AS a, antranetsinan AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM antranetsinan AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE antranetsinan DROP COLUMN id;

CREATE TABLE `antranet70` (`NU_NOTIFIC` varchar(7) DEFAULT NULL,`NM_PACIENT` varchar(100) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` varchar(6) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` varchar(6) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`NU_IDADE_N` varchar(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(20) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL, `NM_COMPLEM` varchar(30) DEFAULT NULL,`NU_CEP` varchar(9) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`ANIMAL` int(1) DEFAULT NULL,`CONDIC_ANI` varchar(1) DEFAULT NULL,`OBSERVACAO` varchar(1) DEFAULT NULL,`FIM_ANIMAL` varchar(1) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`OBS` varchar(254) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `antranet` (`NU_NOTIFIC` varchar(7) DEFAULT NULL,`NM_PACIENT` varchar(100) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` varchar(6) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` varchar(6) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`NU_IDADE_N` varchar(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(20) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL, `NM_COMPLEM` varchar(30) DEFAULT NULL,`NU_CEP` varchar(9) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`ANIMAL` int(1) DEFAULT NULL,`CONDIC_ANI` varchar(1) DEFAULT NULL,`OBSERVACAO` varchar(1) DEFAULT NULL,`FIM_ANIMAL` varchar(1) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`OBS` varchar(254) DEFAULT NULL,`UBS` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into antranet70
SELECT antranetsinan.NU_NOTIFIC, antranetsinan.NM_PACIENT ,antranetsinan.DT_NOTIFIC,CONCAT(RIGHT(antranetsinan.SEM_NOT,2),'SE') AS `SEM_NOT`,antranetsinan.ID_UNIDADE, antranetsinan.DT_SIN_PRI,
   CONCAT(RIGHT(antranetsinan.SEM_PRI,2),'SE') AS `SEM_PRI`, antranetsinan.DT_NASC, CONCAT('0',RIGHT(antranetsinan.NU_IDADE_N,2),'A') AS `NU_IDADE_N`,	antranetsinan.CS_SEXO,
   antranetsinan.ID_CNS_SUS, antranetsinan.ID_DISTRIT, antranetsinan.ID_BAIRRO, antranetsinan.NM_LOGRADO, antranetsinan.NU_NUMERO, antranetsinan.NM_COMPLEM,
   CONCAT(LEFT(antranetsinan.NU_CEP,5),'-',RIGHT(antranetsinan.NU_CEP,3)) AS `NU_CEP`, antranetsinan.NU_DDD_TEL, antranetsinan.NU_TELEFON,antranetsinan.ANIMAL, antranetsinan.CONDIC_ANI,
   antranetsinan.OBSERVACAO, antranetsinan.FIM_ANIMAL, antranetsinan.DT_ENCERRA, antranetsinan.OBS
   FROM antranetsinan WHERE ID_DISTRIT='70';

insert into antranet
SELECT antranet70.`NU_NOTIFIC`,antranet70.`NM_PACIENT`,antranet70.`DT_NOTIFIC`,antranet70.`SEM_NOT`,antranet70.`ID_UNIDADE`,antranet70.`DT_SIN_PRI`,antranet70.`SEM_PRI`,antranet70.`DT_NASC`,antranet70.`NU_IDADE_N`,antranet70.`CS_SEXO`,
    antranet70.`ID_CNS_SUS`,antranet70.`ID_DISTRIT`,antranet70.`ID_DISTRIT`,antranet70.`NM_LOGRADO`,antranet70.`NU_NUMERO`,antranet70.`NM_COMPLEM`,antranet70.`NU_CEP`,antranet70.`NU_DDD_TEL`,antranet70.`NU_TELEFON`,antranet70.`ANIMAL`,
    antranet70.`CONDIC_ANI`,antranet70.`OBSERVACAO`,antranet70.`FIM_ANIMAL`,antranet70.`DT_ENCERRA`,antranet70.`OBS`,ruas.ubs
    FROM antranet70 LEFT JOIN ruas ON antranet70.NU_CEP = ruas.cep;

-- Inserindo campo id como chave primaria
ALTER TABLE `antranet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM antranet AS a, antranet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM antranet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE antranet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `antranet` ADD PRIMARY KEY (`NU_NOTIFIC`);

-- Criando a tabela chikonnet
CREATE TABLE `chikonnet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(5) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` int(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(41) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(19) DEFAULT NULL,`SOUNDEX` varchar(10) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` int(1) DEFAULT NULL, `CS_ESCOL_N` varchar(2) DEFAULT NULL, `ID_CNS_SUS` varchar(15) DEFAULT NULL, `NM_MAE_PAC` varchar(42) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` int(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(4) DEFAULT NULL,`NM_BAIRRO` varchar(52) DEFAULT NULL,`ID_LOGRADO` varchar(10) DEFAULT NULL,`NM_LOGRADO` varchar(37) DEFAULT NULL,`NU_NUMERO` varchar(4) DEFAULT NULL,`NM_COMPLEM` varchar(26) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(33) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`FEBRE` varchar(1) DEFAULT NULL,`MIALGIA` varchar(1) DEFAULT NULL,`CEFALEIA` varchar(1) DEFAULT NULL,`EXANTEMA` varchar(1) DEFAULT NULL,`VOMITO` varchar(1) DEFAULT NULL,`NAUSEA` varchar(1) DEFAULT NULL,`DOR_COSTAS` varchar(1) DEFAULT NULL,`CONJUNTVIT` varchar(1) DEFAULT NULL,`ARTRITE` varchar(1) DEFAULT NULL,`ARTRALGIA` varchar(1) DEFAULT NULL,`PETEQUIA_N` varchar(1) DEFAULT NULL,`LEUCOPENIA` varchar(1) DEFAULT NULL,`LACO` varchar(1) DEFAULT NULL,`DOR_RETRO` varchar(1) DEFAULT NULL,`DIABETES` varchar(1) DEFAULT NULL,`HEMATOLOG` varchar(1) DEFAULT NULL,`HEPATOPAT` varchar(1) DEFAULT NULL,`RENAL` varchar(1) DEFAULT NULL,`HIPERTENSA` varchar(1) DEFAULT NULL,`ACIDO_PEPT` varchar(1) DEFAULT NULL,`AUTO_IMUNE` varchar(1) DEFAULT NULL,`DT_CHIK_S1` varchar(10) DEFAULT NULL,`DT_CHIK_S2` varchar(10) DEFAULT NULL,`DT_PRNT` varchar(10) DEFAULT NULL,`RES_CHIKS1` varchar(1) DEFAULT NULL,`RES_CHIKS2` varchar(1) DEFAULT NULL,`RESUL_PRNT` varchar(1) DEFAULT NULL,`DT_SORO` varchar(10) DEFAULT NULL,`RESUL_SORO` varchar(1) DEFAULT NULL,`DT_NS1` varchar(10) DEFAULT NULL,`RESUL_NS1` varchar(1) DEFAULT NULL,`DT_VIRAL` varchar(10) DEFAULT NULL,`RESUL_VI_N` varchar(1) DEFAULT NULL,`DT_PCR` varchar(10) DEFAULT NULL,`RESUL_PCR_` varchar(1) DEFAULT NULL,`SOROTIPO` varchar(10) DEFAULT NULL,`HISTOPA_N` varchar(1) DEFAULT NULL,`IMUNOH_N` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,`MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`DDD_HOSP` varchar(2) DEFAULT NULL,`TEL_HOSP` varchar(8) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(3) DEFAULT NULL,`CO_BAINF` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(16) DEFAULT NULL,`CLASSI_FIN` varchar(2) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(10) DEFAULT NULL,`CLINC_CHIK` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`ALRM_HIPOT` varchar(10) DEFAULT NULL,`ALRM_PLAQ` varchar(10) DEFAULT NULL,`ALRM_VOM` varchar(10) DEFAULT NULL,`ALRM_SANG` varchar(10) DEFAULT NULL,`ALRM_HEMAT` varchar(10) DEFAULT NULL,`ALRM_ABDOM` varchar(10) DEFAULT NULL,`ALRM_LETAR` varchar(10) DEFAULT NULL,`ALRM_HEPAT` varchar(10) DEFAULT NULL,`ALRM_LIQ` varchar(10) DEFAULT NULL,`DT_ALRM` varchar(10) DEFAULT NULL,`GRAV_PULSO` varchar(10) DEFAULT NULL,`GRAV_CONV` varchar(10) DEFAULT NULL,`GRAV_ENCH` varchar(10) DEFAULT NULL,`GRAV_INSUF` varchar(10) DEFAULT NULL,`GRAV_TAQUI` varchar(10) DEFAULT NULL,`GRAV_EXTRE` varchar(10) DEFAULT NULL,`GRAV_HIPOT` varchar(10) DEFAULT NULL,`GRAV_HEMAT` varchar(10) DEFAULT NULL,`GRAV_MELEN` varchar(10) DEFAULT NULL,`GRAV_METRO` varchar(10) DEFAULT NULL,`GRAV_SANG` varchar(10) DEFAULT NULL,`GRAV_AST` varchar(10) DEFAULT NULL,`GRAV_MIOC` varchar(10) DEFAULT NULL,`GRAV_CONSC` varchar(10) DEFAULT NULL,`GRAV_ORGAO` varchar(10) DEFAULT NULL,`DT_GRAV` varchar(10) DEFAULT NULL,`MANI_HEMOR` varchar(10) DEFAULT NULL,`EPISTAXE` varchar(10) DEFAULT NULL,`GENGIVO` varchar(10) DEFAULT NULL,`METRO` varchar(10) DEFAULT NULL,`PETEQUIAS` varchar(10) DEFAULT NULL,`HEMATURA` varchar(10) DEFAULT NULL,`SANGRAM` varchar(10) DEFAULT NULL,`LACO_N` varchar(10) DEFAULT NULL,`PLASMATICO` varchar(10) DEFAULT NULL,`EVIDENCIA` varchar(10) DEFAULT NULL,`PLAQ_MENOR` varchar(10) DEFAULT NULL,`CON_FHD` varchar(10) DEFAULT NULL,`COMPLICA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(10) DEFAULT NULL,`DS_OBS` varchar(255) DEFAULT NULL,`TP_SISTEMA` varchar(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(10) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` int(1) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` varchar(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Carregando os dados  do excel csv da pasta abaixo ...
LOAD DATA INFILE 'E:/csv/CHIKONET.csv'
INTO TABLE `chikonnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `chikonnet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM chikonnet AS a, chikonnet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM chikonnet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE chikonnet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `chikonnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

-- Criando a tabela dengnet
CREATE TABLE `dengnet` (`NU_NOTIFIC` int(7) DEFAULT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(3) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(54) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(22) DEFAULT NULL,`SOUNDEX` varchar(10) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` varchar(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(52) DEFAULT NULL,`SG_UF` varchar(2) DEFAULT NULL,`ID_MN_RESI` varchar(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(3) DEFAULT NULL,`ID_BAIRRO` varchar(8) DEFAULT NULL,`NM_BAIRRO` varchar(47) DEFAULT NULL,`ID_LOGRADO` varchar(10) DEFAULT NULL,`NM_LOGRADO` varchar(56) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(3) DEFAULT NULL,`ID_GEO2` varchar(4) DEFAULT NULL,`NM_REFEREN` varchar(51) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(3) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`FEBRE` varchar(1) DEFAULT NULL,`MIALGIA` varchar(1) DEFAULT NULL,`CEFALEIA` varchar(1) DEFAULT NULL,`EXANTEMA` varchar(1) DEFAULT NULL,`VOMITO` varchar(1) DEFAULT NULL,`NAUSEA` varchar(1) DEFAULT NULL,`DOR_COSTAS` varchar(1) DEFAULT NULL,`CONJUNTVIT` varchar(1) DEFAULT NULL,`ARTRITE` varchar(1) DEFAULT NULL,`ARTRALGIA` varchar(1) DEFAULT NULL,`PETEQUIA_N` varchar(1) DEFAULT NULL,`LEUCOPENIA` varchar(1) DEFAULT NULL,`LACO` varchar(1) DEFAULT NULL,`DOR_RETRO` varchar(1) DEFAULT NULL,`DIABETES` varchar(1) DEFAULT NULL,`HEMATOLOG` varchar(1) DEFAULT NULL,`HEPATOPAT` varchar(1) DEFAULT NULL,`RENAL` varchar(1) DEFAULT NULL,`HIPERTENSA` varchar(1) DEFAULT NULL,`ACIDO_PEPT` varchar(1) DEFAULT NULL,`AUTO_IMUNE` varchar(1) DEFAULT NULL,`DT_CHIK_S1` varchar(10) DEFAULT NULL,`DT_CHIK_S2` varchar(10) DEFAULT NULL,`DT_PRNT` varchar(10) DEFAULT NULL,`RES_CHIKS1` varchar(1) DEFAULT NULL,`RES_CHIKS2` varchar(1) DEFAULT NULL,`RESUL_PRNT` varchar(1) DEFAULT NULL,`DT_SORO` varchar(10) DEFAULT NULL,`RESUL_SORO` varchar(1) DEFAULT NULL,`DT_NS1` varchar(10) DEFAULT NULL,`RESUL_NS1` varchar(1) DEFAULT NULL,`DT_VIRAL` varchar(10) DEFAULT NULL,
  `RESUL_VI_N` varchar(1) DEFAULT NULL,  `DT_PCR` varchar(10) DEFAULT NULL,`RESUL_PCR_` varchar(1) DEFAULT NULL,  `SOROTIPO` varchar(1) DEFAULT NULL,`HISTOPA_N` varchar(1) DEFAULT NULL,  `IMUNOH_N` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,  `DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,  `MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`DDD_HOSP` varchar(2) DEFAULT NULL,`TEL_HOSP` varchar(8) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(3) DEFAULT NULL,
  `COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(3) DEFAULT NULL,`CO_BAINF` varchar(8) DEFAULT NULL,`NOBAIINF` varchar(25) DEFAULT NULL,`CLASSI_FIN` varchar(2) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(10) DEFAULT NULL,`CLINC_CHIK` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`ALRM_HIPOT` varchar(1) DEFAULT NULL,`ALRM_PLAQ` varchar(1) DEFAULT NULL,`ALRM_VOM` varchar(1) DEFAULT NULL,`ALRM_SANG` varchar(1) DEFAULT NULL,`ALRM_HEMAT` varchar(1) DEFAULT NULL,
  `ALRM_ABDOM` varchar(1) DEFAULT NULL,`ALRM_LETAR` varchar(1) DEFAULT NULL,`ALRM_HEPAT` varchar(1) DEFAULT NULL,`ALRM_LIQ` varchar(1) DEFAULT NULL,`DT_ALRM` varchar(10) DEFAULT NULL,`GRAV_PULSO` varchar(1) DEFAULT NULL,`GRAV_CONV` varchar(1) DEFAULT NULL,`GRAV_ENCH` varchar(1) DEFAULT NULL,`GRAV_INSUF` varchar(1) DEFAULT NULL,`GRAV_TAQUI` varchar(1) DEFAULT NULL,`GRAV_EXTRE` varchar(1) DEFAULT NULL,`GRAV_HIPOT` varchar(1) DEFAULT NULL,`GRAV_HEMAT` varchar(1) DEFAULT NULL,`GRAV_MELEN` varchar(1) DEFAULT NULL,`GRAV_METRO` varchar(1) DEFAULT NULL,`GRAV_SANG` varchar(1) DEFAULT NULL,
  `GRAV_AST` varchar(1) DEFAULT NULL,`GRAV_MIOC` varchar(1) DEFAULT NULL,`GRAV_CONSC` varchar(1) DEFAULT NULL,`GRAV_ORGAO` varchar(1) DEFAULT NULL,`DT_GRAV` varchar(10) DEFAULT NULL,`MANI_HEMOR` varchar(10) DEFAULT NULL, `EPISTAXE` varchar(10) DEFAULT NULL,`GENGIVO` varchar(10) DEFAULT NULL,`METRO` varchar(10) DEFAULT NULL,`PETEQUIAS` varchar(10) DEFAULT NULL,`HEMATURA` varchar(10) DEFAULT NULL,`SANGRAM` varchar(10) DEFAULT NULL,`LACO_N` varchar(10) DEFAULT NULL,`PLASMATICO` varchar(10) DEFAULT NULL,
  `EVIDENCIA` varchar(10) DEFAULT NULL,`PLAQ_MENOR` varchar(10) DEFAULT NULL,`CON_FHD` varchar(10) DEFAULT NULL,`COMPLICA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(10) DEFAULT NULL,`DS_OBS` varchar(255) DEFAULT NULL,`TP_SISTEMA` varchar(1) DEFAULT NULL,`NDUPLIC_N` varchar(1) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(10) DEFAULT NULL,
  `NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` int(1) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` varchar(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA INFILE 'e:/csv/DENGNET.csv'
  INTO TABLE `dengnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `dengnet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM dengnet AS a, dengnet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM dengnet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE dengnet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `dengnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

-- Criando a tabela coquenet
CREATE TABLE `coquenet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(44) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(19) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(45) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(22) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(55) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(30) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`ANT_SENTIN` varchar(1) DEFAULT NULL,`FC_CONTATO` varchar(1) DEFAULT NULL,`OUT_CONTAT` varchar(6) DEFAULT NULL,`NM_CONTATO` varchar(48) DEFAULT NULL,`END_CONTAT` varchar(47) DEFAULT NULL,`CS_VAC_N` varchar(1) DEFAULT NULL,`DT_ULT_DOS` varchar(10) DEFAULT NULL,`DT_CATARRA` varchar(10) DEFAULT NULL,`CS_TOSSE_E` varchar(1) DEFAULT NULL,`CS_TOSSE_P` varchar(1) DEFAULT NULL,`CS_CRISE` varchar(1) DEFAULT NULL,`CS_CIANOSE` varchar(1) DEFAULT NULL,`CS_VOMITOS` varchar(1) DEFAULT NULL,`CS_APNEIA` varchar(1) DEFAULT NULL,`CS_TEMP37` varchar(1) DEFAULT NULL,`CS_TEMP_38` varchar(1) DEFAULT NULL,`CS_OUT_SIN` varchar(1) DEFAULT NULL,`NM_OUT_SIN` varchar(30) DEFAULT NULL,`CS_PNEUMON` varchar(1) DEFAULT NULL,`CS_ENCEFAL` varchar(1) DEFAULT NULL,`CS_DESITRA` varchar(1) DEFAULT NULL,`CS_OTITE` varchar(1) DEFAULT NULL,`CS_DESNUTR` varchar(1) DEFAULT NULL,`CS_OUT_COM` varchar(1) DEFAULT NULL,`NM_OUT_COM` varchar(29) DEFAULT NULL,`CS_HOSPITA` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`COD_UF_HOS` varchar(2) DEFAULT NULL,`COD_MUN_HO` varchar(6) DEFAULT NULL,`COD_HOSP` varchar(7) DEFAULT NULL,`CS_ANTIBIO` varchar(1) DEFAULT NULL,`DT_ADM_ANT` varchar(10) DEFAULT NULL,`CS_COLETA` varchar(1) DEFAULT NULL,`DT_COLETA` varchar(10) DEFAULT NULL,`CS_CULTURA` varchar(1) DEFAULT NULL,`MED_IDEN_C` varchar(1) DEFAULT NULL,`MED_QUAN_C` varchar(2) DEFAULT NULL,`MED_CASO_S` varchar(1) DEFAULT NULL,`COLET_COMU` varchar(1) DEFAULT NULL,`QUAN_COMUN` varchar(1) DEFAULT NULL,`QUAN_POSIT` varchar(1) DEFAULT NULL,`MED_BLOQUE` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Carregando os dados do excel csv da pasta abaixo ...
LOAD DATA INFILE 'e:/csv/COQUENET.csv'
INTO TABLE `coquenet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `coquenet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM coquenet AS a, coquenet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM coquenet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE coquenet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `coquenet` ADD PRIMARY KEY (`NU_NOTIFIC`);

-- Criando a tabela famarnet
CREATE TABLE `famarnet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(44) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(21) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(41) DEFAULT NULL,`SG_UF` varchar(2) DEFAULT NULL,`ID_MN_RESI` varchar(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(30) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(40) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(3) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_INFO_1` varchar(10) DEFAULT NULL,`DT_INFO_2` varchar(10) DEFAULT NULL,`DT_INFO_3` varchar(10) DEFAULT NULL,`CO_UF_OBS1` varchar(2) DEFAULT NULL,`CO_UF_OBS2` varchar(2) DEFAULT NULL,`CO_UF_OBS3` varchar(2) DEFAULT NULL,`CO_MUN_1` varchar(6) DEFAULT NULL,`CO_MUN_2` varchar(6) DEFAULT NULL,`CO_MUN_3` varchar(6) DEFAULT NULL,`CO_PAIS_1` varchar(2) DEFAULT NULL,`CO_PAIS_2` varchar(1) DEFAULT NULL,`CO_PAIS_3` varchar(1) DEFAULT NULL,`DS_TRANS_1` varchar(30) DEFAULT NULL,`DS_TRANS_2` varchar(30) DEFAULT NULL,`DS_TRANS_3` varchar(15) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`EPIZOOTIAS` varchar(1) DEFAULT NULL,`ISOL_VIR_N` varchar(1) DEFAULT NULL,`VETOR_A` varchar(1) DEFAULT NULL,`VACINADO` varchar(1) DEFAULT NULL,`DT_VACINA` varchar(10) DEFAULT NULL,`UF_VAC` varchar(2) DEFAULT NULL,`MUNCI_VAC` varchar(6) DEFAULT NULL,`UNID_VAC` varchar(7) DEFAULT NULL,`DOR_ABDO_N` varchar(1) DEFAULT NULL,`SINT_HEM_N` varchar(1) DEFAULT NULL,`FAGET` varchar(1) DEFAULT NULL,`EXCR_RENA_` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,`MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`BT` varchar(5) DEFAULT NULL,`AST` varchar(5) DEFAULT NULL,`BD` varchar(5) DEFAULT NULL,`ALT` varchar(5) DEFAULT NULL,`DT_COL_1` varchar(10) DEFAULT NULL,`S1_IGM` varchar(1) DEFAULT NULL,`DT_COL_2` varchar(10) DEFAULT NULL,`S2_IGM` varchar(1) DEFAULT NULL,`MAT_COLETA` varchar(1) DEFAULT NULL,`DT_COLETA` varchar(10) DEFAULT NULL,`RES_ISOLAM` varchar(1) DEFAULT NULL,`HISTOPA` varchar(1) DEFAULT NULL,`IMUNOH` varchar(1) DEFAULT NULL,`DT_PTPCR` varchar(10) DEFAULT NULL,`RES_PTPCR` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CLASFIN_ES` varchar(30) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(29) DEFAULT NULL,`LOCALIDADE` varchar(43) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`CON_ATIVID` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,`DS_OBS` varchar(254) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Carregando os dados do excel csv da pasta abaixo ...
LOAD DATA INFILE 'e:/csv/FAMARNET.csv'
INTO TABLE `famarnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `famarnet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM famarnet AS a, famarnet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM famarnet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE `famarnet` DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `famarnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

-- Criando a tabela leptonet --
CREATE TABLE `leptonet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(46) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(21) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(11) DEFAULT NULL,`NM_MAE_PAC` varchar(43) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(30) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(30) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(11) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`ANT_CB_LAM` varchar(1) DEFAULT NULL,`ANT_CB_CRI` varchar(1) DEFAULT NULL,`ANT_CB_CAI` varchar(1) DEFAULT NULL,`ANT_CB_FOS` varchar(1) DEFAULT NULL,`ANT_CB_SIN` varchar(1) DEFAULT NULL,`ANT_CB_PLA` varchar(1) DEFAULT NULL,`ANT_CB_COR` varchar(1) DEFAULT NULL,`ANT_CB_ROE` varchar(1) DEFAULT NULL,`ANT_CB_GRA` varchar(1) DEFAULT NULL,`ANT_CB_TER` varchar(1) DEFAULT NULL,`ANT_CB_LIX` varchar(1) DEFAULT NULL,`ANT_CB_OUT` varchar(1) DEFAULT NULL,`ANT_OU_DES` varchar(30) DEFAULT NULL,`ANT_HUMANO` varchar(1) DEFAULT NULL,`ANT_ANIMAI` varchar(1) DEFAULT NULL,`CLI_DT_ATE` varchar(10) DEFAULT NULL,`CLI_FEBRE` varchar(1) DEFAULT NULL,`CLI_MIALGI` varchar(1) DEFAULT NULL,`CLI_CEFALE` varchar(1) DEFAULT NULL,`CLI_PROST` varchar(1) DEFAULT NULL,`CLI_CONGES` varchar(1) DEFAULT NULL,`CLI_PANTUR` varchar(1) DEFAULT NULL,`CLI_VOMITO` varchar(1) DEFAULT NULL,`CLI_DIARRE` varchar(1) DEFAULT NULL,`CLI_ICTERI` varchar(1) DEFAULT NULL,`CLI_RENAL` varchar(1) DEFAULT NULL,`CLI_RESPIR` varchar(1) DEFAULT NULL,`CLI_CARDIA` varchar(1) DEFAULT NULL,`CLI_HEMOPU` varchar(1) DEFAULT NULL,`CLI_HEMORR` varchar(1) DEFAULT NULL,`CLI_MENING` varchar(1) DEFAULT NULL,`CLI_OUTROS` varchar(1) DEFAULT NULL,`CLI_OTRDES` varchar(30) DEFAULT NULL,`ATE_HOSP` varchar(1) DEFAULT NULL,`ATE_DT_INT` varchar(10) DEFAULT NULL,`ATE_DT_ALT` varchar(10) DEFAULT NULL,`ATE_UF` varchar(2) DEFAULT NULL,`ATE_MUNICI` varchar(6) DEFAULT NULL,`ATE_HOSPIT` varchar(7) DEFAULT NULL,`LAB_DT_1` varchar(10) DEFAULT NULL,`LAB_ELIS_1` varchar(1) DEFAULT NULL,`LAB_DT_2` varchar(10) DEFAULT NULL,`LAB_ELIS_2` varchar(1) DEFAULT NULL,`DTMICRO1` varchar(10) DEFAULT NULL,`MICRO1_S1` varchar(30) DEFAULT NULL,`MICRO1_T_1` varchar(4) DEFAULT NULL,`MICRO1_S_2` varchar(30) DEFAULT NULL,`MICRO1_T_2` varchar(5) DEFAULT NULL,`LAB_MICR_1` varchar(1) DEFAULT NULL,`DTMICRO2` varchar(10) DEFAULT NULL,`MICRO2_S1` varchar(30) DEFAULT NULL,`MICRO2_T_1` varchar(4) DEFAULT NULL,`MICRO2_S_2` varchar(30) DEFAULT NULL,`MICRO2_T_2` varchar(4) DEFAULT NULL,`LAB_MICR_2` varchar(1) DEFAULT NULL,`DTISOLA` varchar(10) DEFAULT NULL,`RES_ISOL` varchar(1) DEFAULT NULL,`DTIMUNO` varchar(10) DEFAULT NULL,`RES_IMUNO` varchar(1) DEFAULT NULL,`DT_PCR` varchar(10) DEFAULT NULL,`RES_PCR` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(10) DEFAULT NULL,`CON_AREA` varchar(1) DEFAULT NULL,`CON_AMBIEN` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`DT_RISCO1` varchar(10) DEFAULT NULL,`DT_RISCO2` varchar(10) DEFAULT NULL,`DT_RISCO3` varchar(10) DEFAULT NULL,`DT_RISCO4` varchar(10) DEFAULT NULL,`CO_MUN_R1` varchar(6) DEFAULT NULL,`CO_MUN_R2` varchar(6) DEFAULT NULL,`CO_MUN_R3` varchar(10) DEFAULT NULL,`CO_MUN_R4` varchar(10) DEFAULT NULL,`CO_UF_R1` varchar(2) DEFAULT NULL,`CO_UF_R2` varchar(2) DEFAULT NULL,`CO_UF_R3` varchar(10) DEFAULT NULL,`CO_UF_R4` varchar(10) DEFAULT NULL,`NO_END_R1` varchar(30) DEFAULT NULL,`NO_END_R2` varchar(39) DEFAULT NULL,`NO_END_R3` varchar(10) DEFAULT NULL,`NO_END_R4` varchar(10) DEFAULT NULL,`NO_LOC_R1` varchar(30) DEFAULT NULL,`NO_LOC_R2` varchar(19) DEFAULT NULL,`NO_LOC_R3` varchar(10) DEFAULT NULL,`NO_LOC_R4` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,`DS_OBS` varchar(254) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Carregando os dados do excel csv da pasta abaixo ...
LOAD DATA INFILE 'e:/csv/LEPTONET.csv'
INTO TABLE `leptonet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria
ALTER TABLE `leptonet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dados de cada registro duplicado (mantém um dos registros)
DELETE a FROM leptonet AS a, leptonet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM leptonet AS a WHERE a.NU_NOTIFIC < 100;

ALTER TABLE leptonet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `leptonet`ADD PRIMARY KEY (`NU_NOTIFIC`);


  -- Criando a tabela exantnet --
  CREATE TABLE `exantnet` (`NU_NOTIFIC` int(7) DEFAULT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(3) DEFAULT NULL,`CS_SUSPEIT` int(1) DEFAULT NULL,
  `DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,
  `ID_REGIONA` int(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(35) DEFAULT NULL,
  `DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(18) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,
  `CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` int(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(38) DEFAULT NULL,
  `SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` int(4) DEFAULT NULL,`ID_DISTRIT` int(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,
  `NM_BAIRRO` varchar(9) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(56) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,
  `NM_CONTATO` varchar(40) DEFAULT NULL,`END_CONTAT` varchar(39) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(16) DEFAULT NULL,
  `NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,
  `NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,
  `DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,
  `CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,
  `ID_OCUPA_N` varchar(6) DEFAULT NULL,`CS_VACINA` int(1) DEFAULT NULL,`DT_DOSE_N` varchar(10) DEFAULT NULL,`CS_FONTE` int(1) DEFAULT NULL,`NM_FONTE` varchar(10) DEFAULT NULL,
  `END_FONTE` varchar(10) DEFAULT NULL,`DT_INICIO_` varchar(10) DEFAULT NULL,`DT_FEBRE` varchar(10) DEFAULT NULL,`ID_TOSSE` int(1) DEFAULT NULL,`ID_CORIZA` varchar(1) DEFAULT NULL,
  `ID_CONJUNT` varchar(1) DEFAULT NULL,`ID_ARTRALG` varchar(1) DEFAULT NULL,`ID_GANGLIO` varchar(1) DEFAULT NULL,`ID_RETRO` varchar(1) DEFAULT NULL,`ID_HOSPIT` int(1) DEFAULT NULL,
  `DT_INTERNA` varchar(10) DEFAULT NULL,`UF_H` varchar(2) DEFAULT NULL,`NM_MUN_HOS` varchar(6) DEFAULT NULL,`NM_HOSPITA` varchar(7) DEFAULT NULL,`DT_COL_1` varchar(10) DEFAULT NULL,
  `DT_COL_2` varchar(10) DEFAULT NULL,`ID_S1_IGM` varchar(1) DEFAULT NULL,`ID_S1_IGG` varchar(1) DEFAULT NULL,`ID_S1_IGM_` varchar(1) DEFAULT NULL,`ID_S1_IGG_` varchar(1) DEFAULT NULL,
  `ID_S1_IG_1` varchar(1) DEFAULT NULL,`ID_S1_IG_2` varchar(1) DEFAULT NULL,`ID_S2_IGM` varchar(10) DEFAULT NULL,`ID_S2_IGG` varchar(10) DEFAULT NULL,`ID_S2_IGM_` varchar(10) DEFAULT NULL,
  `ID_S2_IGG_` varchar(10) DEFAULT NULL,`ID_S2_IG_1` varchar(10) DEFAULT NULL,`ID_S2_IG_2` varchar(10) DEFAULT NULL,`ID_RE_IGM` varchar(10) DEFAULT NULL,`ID_RE_IGG` varchar(10) DEFAULT NULL,
  `ID_RE_IGM_` varchar(10) DEFAULT NULL,`ID_RE_IGG_` varchar(10) DEFAULT NULL,`ID_RE_IG_1` varchar(10) DEFAULT NULL,`ID_RE_IG_2` varchar(10) DEFAULT NULL,`TPEXANTE` varchar(10) DEFAULT NULL,
  `ID_SANGUE` varchar(1) DEFAULT NULL,`ID_URINA` varchar(1) DEFAULT NULL,`ID_SECRECA` varchar(1) DEFAULT NULL,`ID_LIQUOR` varchar(1) DEFAULT NULL,`ID_ETIOLOG` varchar(1) DEFAULT NULL,
  `ETIOL_OUTR` varchar(10) DEFAULT NULL,`CS_VACINAL` varchar(1) DEFAULT NULL,`MENOR_5ANO` varchar(1) DEFAULT NULL,`DE5A14ANOS` varchar(3) DEFAULT NULL,`DE15A39ANO` varchar(3) DEFAULT NULL,
  `INT_TEMPO` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`CS_DESCART` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,
  `COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,
  `NOBAIINF` varchar(8) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,
  `DT_DESC1` varchar(10) DEFAULT NULL,`DT_DESC2` varchar(10) DEFAULT NULL,`DT_DESC3` varchar(10) DEFAULT NULL,`CO_UF_DES1` varchar(2) DEFAULT NULL,`CO_UF_DES2` varchar(2) DEFAULT NULL,
  `CO_UF_DES3` varchar(2) DEFAULT NULL,`MUN_DES1` varchar(6) DEFAULT NULL,`MUN_DES2` varchar(6) DEFAULT NULL,`MUN_DES3` varchar(6) DEFAULT NULL,`PA_DES1` varchar(3) DEFAULT NULL,
  `PA_DES2` varchar(2) DEFAULT NULL,`PA_DES3` varchar(1) DEFAULT NULL,`DS_TRANS1` varchar(5) DEFAULT NULL,`DS_TRANS2` varchar(5) DEFAULT NULL,`DS_TRANS3` varchar(5) DEFAULT NULL,
  `DS_OBS` varchar(254) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

   -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA INFILE 'e:/csv/EXANTNET.csv'
  INTO TABLE `exantnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `exantnet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM exantnet AS a, exantnet AS b WHERE a.NU_NOTIFIC=b.NU_NOTIFIC AND a.id < b.id;
DELETE a FROM exantnet AS a WHERE a.NU_NOTIFIC < 100;

-- Apagando a coluna id criada apenas para encontrar registros duplicados
ALTER TABLE exantnet DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `exantnet`ADD PRIMARY KEY (`NU_NOTIFIC`);


-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `chiku_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA INFILE 'e:/csv/dataChiku.csv'
INTO TABLE `chiku_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `chiku_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM chiku_ial AS a, chiku_ial AS b WHERE a.Requisição=b.Requisição AND a.id < b.id;
DELETE a FROM chiku_ial AS a WHERE a.Requisição < 100;

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `febrea_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA INFILE 'e:/csv/dataFebre.csv'
INTO TABLE `febrea_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `febrea_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM febrea_ial AS a, febrea_ial AS b WHERE a.Requisição=b.Requisição AND a.id < b.id;
DELETE a FROM febrea_ial AS a WHERE a.Requisição < 100;

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `coque_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA INFILE 'e:/csv/datacoque.csv'
INTO TABLE `coque_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `coque_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM coque_ial AS a, coque_ial AS b WHERE a.Requisição=b.Requisição AND a.id < b.id;
DELETE a FROM coque_ial AS a WHERE a.Requisição < 100;

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `dengue_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA INFILE 'e:/csv/dataDengue.csv'
INTO TABLE `dengue_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- ALTER TABLE `dengue_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `dengue_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `zika_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOAD DATA INFILE 'e:/csv/dataZika.csv'
INTO TABLE `zika_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;


-- ALTER TABLE `zika_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `zika_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `sarampo_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(48) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`CPF` VARCHAR(15) NULL,`Setor` varchar(6) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(21) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(20) DEFAULT NULL,`Exame` varchar(27) DEFAULT NULL,`Metodo` varchar(36) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(7) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,
  `Dt. Cadastro` varchar(16) DEFAULT NULL,`Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,
  `Labotório Executor` varchar(29) DEFAULT NULL,`Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(15) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportando novos resultados do ial sarampo
LOAD DATA INFILE 'e:/csv/dataSarampo.csv'
INTO TABLE `sarampo_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- ALTER TABLE `sarampo_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `sarampo_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Criando a tabela resultado_ccz
CREATE TABLE `resultado_ccz` (`ENTRADA` varchar(10) DEFAULT NULL,`PEDIDO` int(8) DEFAULT NULL,`UNIDADE_DE_SAUDE` varchar(30) DEFAULT NULL,`D_A` varchar(17) DEFAULT NULL,
  `UVIS` varchar(30) DEFAULT NULL,`SINAN` varchar(8) DEFAULT NULL,`PACIENTE` varchar(50) DEFAULT NULL,`SEXO` varchar(1) DEFAULT NULL,`NASCIMENTO` varchar(10) DEFAULT NULL,
  `Sintoma` varchar(16) DEFAULT NULL,`Coleta` varchar(16) DEFAULT NULL,`Nr_da_Amostra` varchar(8) DEFAULT NULL,`Resultado_IgM_Panbio` varchar(17) DEFAULT NULL,
  `Kit_IgM` varchar(6) DEFAULT NULL,`Nova_Coleta_Panbio` varchar(3) DEFAULT NULL,`Resultado_IgM_Focus` varchar(17) DEFAULT NULL,`Kit_IgM1` varchar(5) DEFAULT NULL,
  `Nova_Coleta_Focus` varchar(3) DEFAULT NULL,`NS1` varchar(3) DEFAULT NULL,`Nr_AM_NS1` varchar(10) DEFAULT NULL,`Resultado_NS1` varchar(12) DEFAULT NULL,
  `Kit_NS1` varchar(6) DEFAULT NULL,`Data Resultado` varchar(10) DEFAULT NULL,`OBSERVACAO` varchar(57) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportando novos resultados do ccz dengue
LOAD DATA INFILE 'e:/csv/RadGridExport.csv'
INTO TABLE `resultado_ccz`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `resultado_ccz` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM resultado_ccz AS a, resultado_ccz AS b WHERE a.PEDIDO=b.PEDIDO AND a.id < b.id;
DELETE a FROM resultado_ccz AS a WHERE a.PEDIDO < 100;

-- Apagando a coluna id criada apenas para encontrar registros duplicados
ALTER TABLE resultado_ccz DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `resultado_ccz`ADD PRIMARY KEY (`PEDIDO`);

-- Criando a tabela resultado_ccz_lepto
CREATE TABLE `resultado_ccz_lepto` ( `ENTRADA` varchar(10) DEFAULT NULL, `Nº Pedido` int(8) DEFAULT NULL, `UNDADE_DE_SAUDE` varchar(32) DEFAULT NULL, `D_A` varchar(15) DEFAULT NULL, `UVIS` varchar(30) DEFAULT NULL,
     `SINAN` varchar(7) DEFAULT NULL, `PACIENTE` varchar(43) DEFAULT NULL, `Sexo` varchar(1) DEFAULT NULL, `Nascimento` varchar(10) DEFAULT NULL, `Coleta` varchar(13) DEFAULT NULL,
     `RES_ELISA_PANBIO` varchar(12) DEFAULT NULL, `CO_PANBIO` varchar(4) DEFAULT NULL, `DO_PANBIO` varchar(6) DEFAULT NULL, `RES_ELISA_SERION` varchar(10) DEFAULT NULL, `CO_SERION` varchar(10) DEFAULT NULL,
     `DO_SERION` varchar(10) DEFAULT NULL, `RES_MAT` varchar(12) DEFAULT NULL, `NOVA_COLETA` varchar(3) DEFAULT NULL, `1o_SOROVAR` varchar(19) DEFAULT NULL, `1o_TIT` varchar(5) DEFAULT NULL,
     `2o_SOROVAR` varchar(11) DEFAULT NULL, `2o_TIT` varchar(4) DEFAULT NULL, `3o_SOROVAR` varchar(11) DEFAULT NULL, `3o_TIT` varchar(5) DEFAULT NULL, `4o_SOROVAR` varchar(11) DEFAULT NULL,
     `4o_TIT` varchar(5) DEFAULT NULL,  `5o_SOROVAR` varchar(11) DEFAULT NULL, `5o_TIT` varchar(5) DEFAULT NULL, `6o_SOROVAR` varchar(10) DEFAULT NULL, `6o_TIT` varchar(4) DEFAULT NULL,
     `7o_SOROVAR` varchar(9) DEFAULT NULL, `7o_TIT` varchar(4) DEFAULT NULL,  `8o_SOROVAR` varchar(10) DEFAULT NULL, `8o_TIT` varchar(10) DEFAULT NULL, `9o_SOROVAR` varchar(10) DEFAULT NULL,
     `9o_TIT` varchar(10) DEFAULT NULL, `10o_SOROVAR` varchar(10) DEFAULT NULL, `10o_TIT` varchar(10) DEFAULT NULL, `11o_SOROVAR` varchar(10) DEFAULT NULL, `11o_TIT` varchar(10) DEFAULT NULL,
     `12o_SOROVAR` varchar(10) DEFAULT NULL, `12o_TIT` varchar(10) DEFAULT NULL, `13_SOROVAR` varchar(10) DEFAULT NULL, `13_TIT` varchar(10) DEFAULT NULL,
     `14o_SOROVAR` varchar(10) DEFAULT NULL, `14o_TIT` varchar(10) DEFAULT NULL, `15o_SOROVAR` varchar(10) DEFAULT NULL, `15o_TIT` varchar(10) DEFAULT NULL, `16o_SOROVAR` varchar(10) DEFAULT NULL,
     `16o_TIT` varchar(10) DEFAULT NULL, `17o_SOROVAR` varchar(10) DEFAULT NULL, `17o_TIT` varchar(10) DEFAULT NULL, `18o_SOROVAR` varchar(10) DEFAULT NULL, `18o_TIT` varchar(10) DEFAULT NULL,
     `19o_SOROVAR` varchar(10) DEFAULT NULL, `19o_TIT` varchar(10) DEFAULT NULL, `Data Resultado` varchar(10) DEFAULT NULL, `OBSERVACAO` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportando novos resultados do ccz dengue
LOAD DATA INFILE 'e:/csv/RadGridExportLepto.csv'
INTO TABLE `resultado_ccz_lepto`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `resultado_ccz_lepto` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM resultado_ccz_lepto AS a, resultado_ccz_lepto AS b WHERE a.`Nº Pedido`=b.`Nº Pedido` AND a.id < b.id;
DELETE a FROM resultado_ccz_lepto AS a WHERE a.`Nº Pedido` < 100;

-- Apagando a coluna id criada apenas para encontrar registros duplicados
ALTER TABLE resultado_ccz_lepto DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `resultado_ccz_lepto`ADD PRIMARY KEY (`Nº Pedido`);

-- Criando a tabela resultado_esporo
CREATE TABLE `resultado_esporo` (`Data_Pedido` varchar(10) DEFAULT NULL,`Nr_Pedido` int(8) NOT NULL,`SeqProcedimento` int(1) DEFAULT NULL,`Solicitante` varchar(31) DEFAULT NULL,
    `Distrito` varchar(15) DEFAULT NULL,`SUVIS` varchar(30) DEFAULT NULL,`SINAN` varchar(2) DEFAULT NULL,`Nome` varchar(24) DEFAULT NULL,`Especie` varchar(6) DEFAULT NULL,
    `Proprietario` varchar(10) DEFAULT NULL,`Endereco` varchar(50) DEFAULT NULL,`Numero` varchar(6) DEFAULT NULL,`Bairro` varchar(10) DEFAULT NULL,`CEP` varchar(10) DEFAULT NULL,
    `Resultado` varchar(8) DEFAULT NULL,`Identificacao1` varchar(13) DEFAULT NULL,`Identificacao2` varchar(10) DEFAULT NULL,`LIBERACAO_EM` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Exportando novos resultados do ccz esporo
LOAD DATA INFILE 'e:/csv/resultado_esporo.csv'
INTO TABLE `resultado_esporo`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS;

-- Inserindo campo id como chave primaria para encontrar registros duplicados
ALTER TABLE `resultado_esporo` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Comando SQL para apagar um ou mais dos de cada registro duplicado (mantém um dos registros)
DELETE a FROM resultado_esporo AS a, resultado_esporo AS b WHERE a.Nr_Pedido=b.Nr_Pedido AND a.id < b.id;
DELETE a FROM resultado_esporo AS a WHERE a.Nr_Pedido < 100;

-- Apagando a coluna id criada apenas para encontrar registros duplicados
ALTER TABLE `resultado_esporo` DROP COLUMN id;

-- Inserindo chave primária
ALTER TABLE `resultado_esporo` ADD PRIMARY KEY (`Nr_Pedido`);

-- J11n3ts1n@n	J11	COVID (ESUS)
-- A920n3ts1n@n	A920	CHIKUNGUNYA
-- A379n3ts1n@n	A379	COQUELUCHE
-- B09n3ts1n@n	B09	DOENCAS EXANTEMATICAS
-- A959n3ts1n@n	A959	FEBRE AMARELA
-- A279n3ts1n@n	A279	LEPTOSPIROSE
