-- Comandos sql para apagar tabelas do banco de dados --
-- Autor: Rodolfo Romaioli Ribeiro de Jesus - rodolfo.romaioli@gmail.com
-- Criado: 15/05/2018 11:30
-- Alterado em 01/04/2019 às 10:26

-- DROP TABLE chikonnet, coquenet, dengnet, famarnet, leptonet, exantnet, chiku_ial,coque_ial,dengue_ial,febrea_ial,zika_ial,sarampo_ial,resultado_ccz,resultado_ccz_lepto;

-- Comandos sql para atualizar banco de dados --
-- Autor: Rodolfo Romaioli Ribeiro de Jesus - rodolfo.romaioli@gmail.com
-- Criado: 15/05/2018 11:30
-- Alterado em 20/12/2012 às 10:26

-- Script criado para carregar tabelas extraídas de bancos de dados -> SinanNet, Getwin e GAL-Instituto Adolfo Lutz
--
-- Carregando

  -- Criando a tabela chikonnet
  CREATE TABLE `chikonnet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(5) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` int(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(41) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(19) DEFAULT NULL,`SOUNDEX` varchar(10) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` int(1) DEFAULT NULL, `CS_ESCOL_N` varchar(2) DEFAULT NULL, `ID_CNS_SUS` varchar(15) DEFAULT NULL, `NM_MAE_PAC` varchar(42) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` int(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(4) DEFAULT NULL,`NM_BAIRRO` varchar(52) DEFAULT NULL,`ID_LOGRADO` varchar(10) DEFAULT NULL,`NM_LOGRADO` varchar(37) DEFAULT NULL,`NU_NUMERO` varchar(4) DEFAULT NULL,`NM_COMPLEM` varchar(26) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(33) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`FEBRE` varchar(1) DEFAULT NULL,`MIALGIA` varchar(1) DEFAULT NULL,`CEFALEIA` varchar(1) DEFAULT NULL,`EXANTEMA` varchar(1) DEFAULT NULL,`VOMITO` varchar(1) DEFAULT NULL,`NAUSEA` varchar(1) DEFAULT NULL,`DOR_COSTAS` varchar(1) DEFAULT NULL,`CONJUNTVIT` varchar(1) DEFAULT NULL,`ARTRITE` varchar(1) DEFAULT NULL,`ARTRALGIA` varchar(1) DEFAULT NULL,`PETEQUIA_N` varchar(1) DEFAULT NULL,`LEUCOPENIA` varchar(1) DEFAULT NULL,`LACO` varchar(1) DEFAULT NULL,`DOR_RETRO` varchar(1) DEFAULT NULL,`DIABETES` varchar(1) DEFAULT NULL,`HEMATOLOG` varchar(1) DEFAULT NULL,`HEPATOPAT` varchar(1) DEFAULT NULL,`RENAL` varchar(1) DEFAULT NULL,`HIPERTENSA` varchar(1) DEFAULT NULL,`ACIDO_PEPT` varchar(1) DEFAULT NULL,`AUTO_IMUNE` varchar(1) DEFAULT NULL,`DT_CHIK_S1` varchar(10) DEFAULT NULL,`DT_CHIK_S2` varchar(10) DEFAULT NULL,`DT_PRNT` varchar(10) DEFAULT NULL,`RES_CHIKS1` varchar(1) DEFAULT NULL,`RES_CHIKS2` varchar(1) DEFAULT NULL,`RESUL_PRNT` varchar(1) DEFAULT NULL,`DT_SORO` varchar(10) DEFAULT NULL,`RESUL_SORO` varchar(1) DEFAULT NULL,`DT_NS1` varchar(10) DEFAULT NULL,`RESUL_NS1` varchar(1) DEFAULT NULL,`DT_VIRAL` varchar(10) DEFAULT NULL,`RESUL_VI_N` varchar(1) DEFAULT NULL,`DT_PCR` varchar(10) DEFAULT NULL,`RESUL_PCR_` varchar(1) DEFAULT NULL,`SOROTIPO` varchar(10) DEFAULT NULL,`HISTOPA_N` varchar(1) DEFAULT NULL,`IMUNOH_N` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,`MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`DDD_HOSP` varchar(2) DEFAULT NULL,`TEL_HOSP` varchar(8) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(3) DEFAULT NULL,`CO_BAINF` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(16) DEFAULT NULL,`CLASSI_FIN` varchar(2) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(10) DEFAULT NULL,`CLINC_CHIK` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`ALRM_HIPOT` varchar(10) DEFAULT NULL,`ALRM_PLAQ` varchar(10) DEFAULT NULL,`ALRM_VOM` varchar(10) DEFAULT NULL,`ALRM_SANG` varchar(10) DEFAULT NULL,`ALRM_HEMAT` varchar(10) DEFAULT NULL,`ALRM_ABDOM` varchar(10) DEFAULT NULL,`ALRM_LETAR` varchar(10) DEFAULT NULL,`ALRM_HEPAT` varchar(10) DEFAULT NULL,`ALRM_LIQ` varchar(10) DEFAULT NULL,`DT_ALRM` varchar(10) DEFAULT NULL,`GRAV_PULSO` varchar(10) DEFAULT NULL,`GRAV_CONV` varchar(10) DEFAULT NULL,`GRAV_ENCH` varchar(10) DEFAULT NULL,`GRAV_INSUF` varchar(10) DEFAULT NULL,`GRAV_TAQUI` varchar(10) DEFAULT NULL,`GRAV_EXTRE` varchar(10) DEFAULT NULL,`GRAV_HIPOT` varchar(10) DEFAULT NULL,`GRAV_HEMAT` varchar(10) DEFAULT NULL,`GRAV_MELEN` varchar(10) DEFAULT NULL,`GRAV_METRO` varchar(10) DEFAULT NULL,`GRAV_SANG` varchar(10) DEFAULT NULL,`GRAV_AST` varchar(10) DEFAULT NULL,`GRAV_MIOC` varchar(10) DEFAULT NULL,`GRAV_CONSC` varchar(10) DEFAULT NULL,`GRAV_ORGAO` varchar(10) DEFAULT NULL,`DT_GRAV` varchar(10) DEFAULT NULL,`MANI_HEMOR` varchar(10) DEFAULT NULL,`EPISTAXE` varchar(10) DEFAULT NULL,`GENGIVO` varchar(10) DEFAULT NULL,`METRO` varchar(10) DEFAULT NULL,`PETEQUIAS` varchar(10) DEFAULT NULL,`HEMATURA` varchar(10) DEFAULT NULL,`SANGRAM` varchar(10) DEFAULT NULL,`LACO_N` varchar(10) DEFAULT NULL,`PLASMATICO` varchar(10) DEFAULT NULL,`EVIDENCIA` varchar(10) DEFAULT NULL,`PLAQ_MENOR` varchar(10) DEFAULT NULL,`CON_FHD` varchar(10) DEFAULT NULL,`COMPLICA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(10) DEFAULT NULL,`DS_OBS` varchar(255) DEFAULT NULL,`TP_SISTEMA` varchar(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(10) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` int(1) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` varchar(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL)
  ENGINE=InnoDB DEFAULT CHARSET=utf8;
    -- Inserindo chave primária
  ALTER TABLE `chikonnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

  -- Carregando os dados  do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/CHIKONET.csv'
  INTO TABLE `chikonnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
  (`NU_NOTIFIC`,`TP_NOT`,`ID_AGRAVO`,`DT_NOTIFIC`,`SEM_NOT`,`NU_ANO`,`SG_UF_NOT`,`ID_MUNICIP`,`ID_REGIONA`,`ID_UNIDADE`,`DT_SIN_PRI`,`SEM_PRI`,`NM_PACIENT`,`DT_NASC`,`FONETICA_N`,`SOUNDEX`,`NU_IDADE_N`,`CS_SEXO`,`CS_GESTANT`,`CS_RACA`,`CS_ESCOL_N`,`ID_CNS_SUS`,`NM_MAE_PAC`,`SG_UF`,`ID_MN_RESI`,`ID_RG_RESI`,`ID_DISTRIT`,`ID_BAIRRO`,`NM_BAIRRO`,`ID_LOGRADO`,`NM_LOGRADO`,`NU_NUMERO`,`NM_COMPLEM`,`ID_GEO1`,`ID_GEO2`,`NM_REFEREN`,`NU_CEP`,`NU_DDD_TEL`,`NU_TELEFON`,`CS_ZONA`,`ID_PAIS`,`DT_INVEST`,`ID_OCUPA_N`,`FEBRE`,`MIALGIA`,`CEFALEIA`,`EXANTEMA`,`VOMITO`,`NAUSEA`,`DOR_COSTAS`,`CONJUNTVIT`,`ARTRITE`,`ARTRALGIA`,`PETEQUIA_N`,`LEUCOPENIA`,`LACO`,`DOR_RETRO`,`DIABETES`,`HEMATOLOG`,`HEPATOPAT`,`RENAL`,`HIPERTENSA`,`ACIDO_PEPT`,`AUTO_IMUNE`,`DT_CHIK_S1`,`DT_CHIK_S2`,`DT_PRNT`,`RES_CHIKS1`,`RES_CHIKS2`,`RESUL_PRNT`,`DT_SORO`,`RESUL_SORO`,`DT_NS1`,`RESUL_NS1`,`DT_VIRAL`,`RESUL_VI_N`,`DT_PCR`,`RESUL_PCR_`,`SOROTIPO`,`HISTOPA_N`,`IMUNOH_N`,`HOSPITALIZ`,`DT_INTERNA`,`UF`,`MUNICIPIO`,`HOSPITAL`,
  `DDD_HOSP`,`TEL_HOSP`,`TPAUTOCTO`,`COUFINF`,`COPAISINF`,`COMUNINF`,`CODISINF`,`CO_BAINF`,`NOBAIINF`,`CLASSI_FIN`,`CRITERIO`,`DOENCA_TRA`,`CLINC_CHIK`,`EVOLUCAO`,`DT_OBITO`,`DT_ENCERRA`,`ALRM_HIPOT`,`ALRM_PLAQ`,`ALRM_VOM`,`ALRM_SANG`,`ALRM_HEMAT`,`ALRM_ABDOM`,`ALRM_LETAR`,`ALRM_HEPAT`,`ALRM_LIQ`,`DT_ALRM`,`GRAV_PULSO`,`GRAV_CONV`,`GRAV_ENCH`,`GRAV_INSUF`,`GRAV_TAQUI`,`GRAV_EXTRE`,`GRAV_HIPOT`,`GRAV_HEMAT`,`GRAV_MELEN`,`GRAV_METRO`,`GRAV_SANG`,`GRAV_AST`,`GRAV_MIOC`,`GRAV_CONSC`,`GRAV_ORGAO`,`DT_GRAV`,`MANI_HEMOR`,`EPISTAXE`,`GENGIVO`,`METRO`,`PETEQUIAS`,`HEMATURA`,`SANGRAM`,`LACO_N`,`PLASMATICO`,`EVIDENCIA`,`PLAQ_MENOR`,`CON_FHD`,`COMPLICA`,`NU_LOTE_I`,`DS_OBS`,`TP_SISTEMA`,`NDUPLIC_N`,`DT_DIGITA`,`DT_TRANSUS`,`DT_TRANSDM`,`DT_TRANSSM`,`DT_TRANSRM`,`DT_TRANSRS`,`DT_TRANSSE`,`NU_LOTE_V`,`NU_LOTE_H`,`CS_FLXRET`,`FLXRECEBI`,`IDENT_MICR`,`MIGRADO_W`);

-- Criando a tabela dengnet
CREATE TABLE `dengnet` (`NU_NOTIFIC` int(7) DEFAULT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(3) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(54) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(22) DEFAULT NULL,`SOUNDEX` varchar(10) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` varchar(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(52) DEFAULT NULL,`SG_UF` varchar(2) DEFAULT NULL,`ID_MN_RESI` varchar(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(3) DEFAULT NULL,`ID_BAIRRO` varchar(8) DEFAULT NULL,`NM_BAIRRO` varchar(47) DEFAULT NULL,`ID_LOGRADO` varchar(10) DEFAULT NULL,`NM_LOGRADO` varchar(56) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(3) DEFAULT NULL,`ID_GEO2` varchar(4) DEFAULT NULL,`NM_REFEREN` varchar(51) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(3) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`FEBRE` varchar(1) DEFAULT NULL,`MIALGIA` varchar(1) DEFAULT NULL,`CEFALEIA` varchar(1) DEFAULT NULL,`EXANTEMA` varchar(1) DEFAULT NULL,`VOMITO` varchar(1) DEFAULT NULL,`NAUSEA` varchar(1) DEFAULT NULL,`DOR_COSTAS` varchar(1) DEFAULT NULL,`CONJUNTVIT` varchar(1) DEFAULT NULL,`ARTRITE` varchar(1) DEFAULT NULL,`ARTRALGIA` varchar(1) DEFAULT NULL,`PETEQUIA_N` varchar(1) DEFAULT NULL,`LEUCOPENIA` varchar(1) DEFAULT NULL,`LACO` varchar(1) DEFAULT NULL,`DOR_RETRO` varchar(1) DEFAULT NULL,`DIABETES` varchar(1) DEFAULT NULL,`HEMATOLOG` varchar(1) DEFAULT NULL,`HEPATOPAT` varchar(1) DEFAULT NULL,`RENAL` varchar(1) DEFAULT NULL,`HIPERTENSA` varchar(1) DEFAULT NULL,`ACIDO_PEPT` varchar(1) DEFAULT NULL,`AUTO_IMUNE` varchar(1) DEFAULT NULL,`DT_CHIK_S1` varchar(10) DEFAULT NULL,`DT_CHIK_S2` varchar(10) DEFAULT NULL,`DT_PRNT` varchar(10) DEFAULT NULL,`RES_CHIKS1` varchar(1) DEFAULT NULL,`RES_CHIKS2` varchar(1) DEFAULT NULL,`RESUL_PRNT` varchar(1) DEFAULT NULL,`DT_SORO` varchar(10) DEFAULT NULL,`RESUL_SORO` varchar(1) DEFAULT NULL,`DT_NS1` varchar(10) DEFAULT NULL,`RESUL_NS1` varchar(1) DEFAULT NULL,`DT_VIRAL` varchar(10) DEFAULT NULL,
  `RESUL_VI_N` varchar(1) DEFAULT NULL,  `DT_PCR` varchar(10) DEFAULT NULL,`RESUL_PCR_` varchar(1) DEFAULT NULL,  `SOROTIPO` varchar(1) DEFAULT NULL,`HISTOPA_N` varchar(1) DEFAULT NULL,  `IMUNOH_N` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,  `DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,  `MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`DDD_HOSP` varchar(2) DEFAULT NULL,`TEL_HOSP` varchar(8) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(3) DEFAULT NULL,
  `COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(3) DEFAULT NULL,`CO_BAINF` varchar(8) DEFAULT NULL,`NOBAIINF` varchar(25) DEFAULT NULL,`CLASSI_FIN` varchar(2) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(10) DEFAULT NULL,`CLINC_CHIK` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`ALRM_HIPOT` varchar(1) DEFAULT NULL,`ALRM_PLAQ` varchar(1) DEFAULT NULL,`ALRM_VOM` varchar(1) DEFAULT NULL,`ALRM_SANG` varchar(1) DEFAULT NULL,`ALRM_HEMAT` varchar(1) DEFAULT NULL,
  `ALRM_ABDOM` varchar(1) DEFAULT NULL,`ALRM_LETAR` varchar(1) DEFAULT NULL,`ALRM_HEPAT` varchar(1) DEFAULT NULL,`ALRM_LIQ` varchar(1) DEFAULT NULL,`DT_ALRM` varchar(10) DEFAULT NULL,`GRAV_PULSO` varchar(1) DEFAULT NULL,`GRAV_CONV` varchar(1) DEFAULT NULL,`GRAV_ENCH` varchar(1) DEFAULT NULL,`GRAV_INSUF` varchar(1) DEFAULT NULL,`GRAV_TAQUI` varchar(1) DEFAULT NULL,`GRAV_EXTRE` varchar(1) DEFAULT NULL,`GRAV_HIPOT` varchar(1) DEFAULT NULL,`GRAV_HEMAT` varchar(1) DEFAULT NULL,`GRAV_MELEN` varchar(1) DEFAULT NULL,`GRAV_METRO` varchar(1) DEFAULT NULL,`GRAV_SANG` varchar(1) DEFAULT NULL,
  `GRAV_AST` varchar(1) DEFAULT NULL,`GRAV_MIOC` varchar(1) DEFAULT NULL,`GRAV_CONSC` varchar(1) DEFAULT NULL,`GRAV_ORGAO` varchar(1) DEFAULT NULL,`DT_GRAV` varchar(10) DEFAULT NULL,`MANI_HEMOR` varchar(10) DEFAULT NULL, `EPISTAXE` varchar(10) DEFAULT NULL,`GENGIVO` varchar(10) DEFAULT NULL,`METRO` varchar(10) DEFAULT NULL,`PETEQUIAS` varchar(10) DEFAULT NULL,`HEMATURA` varchar(10) DEFAULT NULL,`SANGRAM` varchar(10) DEFAULT NULL,`LACO_N` varchar(10) DEFAULT NULL,`PLASMATICO` varchar(10) DEFAULT NULL,
  `EVIDENCIA` varchar(10) DEFAULT NULL,`PLAQ_MENOR` varchar(10) DEFAULT NULL,`CON_FHD` varchar(10) DEFAULT NULL,`COMPLICA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(10) DEFAULT NULL,`DS_OBS` varchar(255) DEFAULT NULL,`TP_SISTEMA` varchar(1) DEFAULT NULL,`NDUPLIC_N` varchar(1) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(10) DEFAULT NULL,
  `NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` int(1) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` varchar(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserindo chave primária
ALTER TABLE `dengnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/DENGNET.csv'
  INTO TABLE `dengnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
  (`NU_NOTIFIC`, `TP_NOT`, `ID_AGRAVO`, `DT_NOTIFIC`, `SEM_NOT`, `NU_ANO`, `SG_UF_NOT`, `ID_MUNICIP`, `ID_REGIONA`, `ID_UNIDADE`, `DT_SIN_PRI`, `SEM_PRI`, `NM_PACIENT`, `DT_NASC`, `FONETICA_N`, `SOUNDEX`, `NU_IDADE_N`, `CS_SEXO`, `CS_GESTANT`, `CS_RACA`, `CS_ESCOL_N`, `ID_CNS_SUS`, `NM_MAE_PAC`, `SG_UF`, `ID_MN_RESI`, `ID_RG_RESI`, `ID_DISTRIT`, `ID_BAIRRO`, `NM_BAIRRO`, `ID_LOGRADO`, `NM_LOGRADO`, `NU_NUMERO`, `NM_COMPLEM`, `ID_GEO1`, `ID_GEO2`, `NM_REFEREN`, `NU_CEP`, `NU_DDD_TEL`, `NU_TELEFON`, `CS_ZONA`, `ID_PAIS`, `DT_INVEST`, `ID_OCUPA_N`, `FEBRE`, `MIALGIA`, `CEFALEIA`, `EXANTEMA`, `VOMITO`, `NAUSEA`, `DOR_COSTAS`, `CONJUNTVIT`, `ARTRITE`, `ARTRALGIA`, `PETEQUIA_N`, `LEUCOPENIA`, `LACO`, `DOR_RETRO`,
   `DIABETES`, `HEMATOLOG`, `HEPATOPAT`, `RENAL`, `HIPERTENSA`, `ACIDO_PEPT`, `AUTO_IMUNE`, `DT_CHIK_S1`, `DT_CHIK_S2`, `DT_PRNT`, `RES_CHIKS1`, `RES_CHIKS2`, `RESUL_PRNT`, `DT_SORO`, `RESUL_SORO`, `DT_NS1`, `RESUL_NS1`, `DT_VIRAL`, `RESUL_VI_N`, `DT_PCR`, `RESUL_PCR_`, `SOROTIPO`, `HISTOPA_N`, `IMUNOH_N`, `HOSPITALIZ`, `DT_INTERNA`, `UF`, `MUNICIPIO`, `HOSPITAL`, `DDD_HOSP`, `TEL_HOSP`, `TPAUTOCTO`, `COUFINF`, `COPAISINF`, `COMUNINF`, `CODISINF`, `CO_BAINF`, `NOBAIINF`, `CLASSI_FIN`, `CRITERIO`, `DOENCA_TRA`, `CLINC_CHIK`, `EVOLUCAO`, `DT_OBITO`, `DT_ENCERRA`, `ALRM_HIPOT`, `ALRM_PLAQ`, `ALRM_VOM`, `ALRM_SANG`, `ALRM_HEMAT`, `ALRM_ABDOM`, `ALRM_LETAR`, `ALRM_HEPAT`, `ALRM_LIQ`, `DT_ALRM`, `GRAV_PULSO`, `GRAV_CONV`, `GRAV_ENCH`, `GRAV_INSUF`, `GRAV_TAQUI`, `GRAV_EXTRE`, `GRAV_HIPOT`, `GRAV_HEMAT`, `GRAV_MELEN`, `GRAV_METRO`, `GRAV_SANG`, `GRAV_AST`, `GRAV_MIOC`, `GRAV_CONSC`, `GRAV_ORGAO`, `DT_GRAV`, `MANI_HEMOR`, `EPISTAXE`, `GENGIVO`, `METRO`, `PETEQUIAS`, `HEMATURA`, `SANGRAM`, `LACO_N`, `PLASMATICO`, `EVIDENCIA`, `PLAQ_MENOR`, `CON_FHD`, `COMPLICA`, `NU_LOTE_I`, `DS_OBS`, `TP_SISTEMA`, `NDUPLIC_N`, `DT_DIGITA`, `DT_TRANSUS`, `DT_TRANSDM`, `DT_TRANSSM`, `DT_TRANSRM`, `DT_TRANSRS`, `DT_TRANSSE`, `NU_LOTE_V`, `NU_LOTE_H`, `CS_FLXRET`, `FLXRECEBI`, `IDENT_MICR`, `MIGRADO_W`);

  -- Criando a tabela coquenet
  CREATE TABLE `coquenet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(44) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(19) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(45) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(22) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(55) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(30) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`ANT_SENTIN` varchar(1) DEFAULT NULL,`FC_CONTATO` varchar(1) DEFAULT NULL,`OUT_CONTAT` varchar(6) DEFAULT NULL,`NM_CONTATO` varchar(48) DEFAULT NULL,`END_CONTAT` varchar(47) DEFAULT NULL,`CS_VAC_N` varchar(1) DEFAULT NULL,`DT_ULT_DOS` varchar(10) DEFAULT NULL,`DT_CATARRA` varchar(10) DEFAULT NULL,`CS_TOSSE_E` varchar(1) DEFAULT NULL,`CS_TOSSE_P` varchar(1) DEFAULT NULL,`CS_CRISE` varchar(1) DEFAULT NULL,`CS_CIANOSE` varchar(1) DEFAULT NULL,`CS_VOMITOS` varchar(1) DEFAULT NULL,`CS_APNEIA` varchar(1) DEFAULT NULL,`CS_TEMP37` varchar(1) DEFAULT NULL,`CS_TEMP_38` varchar(1) DEFAULT NULL,`CS_OUT_SIN` varchar(1) DEFAULT NULL,`NM_OUT_SIN` varchar(30) DEFAULT NULL,`CS_PNEUMON` varchar(1) DEFAULT NULL,`CS_ENCEFAL` varchar(1) DEFAULT NULL,`CS_DESITRA` varchar(1) DEFAULT NULL,`CS_OTITE` varchar(1) DEFAULT NULL,`CS_DESNUTR` varchar(1) DEFAULT NULL,`CS_OUT_COM` varchar(1) DEFAULT NULL,`NM_OUT_COM` varchar(29) DEFAULT NULL,`CS_HOSPITA` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`COD_UF_HOS` varchar(2) DEFAULT NULL,`COD_MUN_HO` varchar(6) DEFAULT NULL,`COD_HOSP` varchar(7) DEFAULT NULL,`CS_ANTIBIO` varchar(1) DEFAULT NULL,`DT_ADM_ANT` varchar(10) DEFAULT NULL,`CS_COLETA` varchar(1) DEFAULT NULL,`DT_COLETA` varchar(10) DEFAULT NULL,`CS_CULTURA` varchar(1) DEFAULT NULL,`MED_IDEN_C` varchar(1) DEFAULT NULL,`MED_QUAN_C` varchar(2) DEFAULT NULL,`MED_CASO_S` varchar(1) DEFAULT NULL,`COLET_COMU` varchar(1) DEFAULT NULL,`QUAN_COMUN` varchar(1) DEFAULT NULL,`QUAN_POSIT` varchar(1) DEFAULT NULL,`MED_BLOQUE` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    -- Inserindo chave primária
  ALTER TABLE `coquenet` ADD PRIMARY KEY (`NU_NOTIFIC`);

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/COQUENET.csv'
  INTO TABLE `coquenet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
  (`NU_NOTIFIC`,`TP_NOT`,`ID_AGRAVO`,`DT_NOTIFIC`,`SEM_NOT`,`NU_ANO`,`SG_UF_NOT`,`ID_MUNICIP`,`ID_REGIONA`,`ID_UNIDADE`,`DT_SIN_PRI`,`SEM_PRI`,`NM_PACIENT`,`DT_NASC`,`FONETICA_N`,`SOUNDEX`,`NU_IDADE_N`,`CS_SEXO`,`CS_GESTANT`,`CS_RACA`,`CS_ESCOL_N`,`ID_CNS_SUS`,`NM_MAE_PAC`,`SG_UF`,`ID_MN_RESI`,`ID_RG_RESI`,`ID_DISTRIT`,`ID_BAIRRO`,`NM_BAIRRO`,`ID_LOGRADO`,`NM_LOGRADO`,`NU_NUMERO`,`NM_COMPLEM`,`ID_GEO1`,`ID_GEO2`,`NM_REFEREN`,`NU_CEP`,`NU_DDD_TEL`,`NU_TELEFON`,`CS_ZONA`,`ID_PAIS`,`NDUPLIC_N`,`DT_DIGITA`,`DT_TRANSUS`,`DT_TRANSDM`,`DT_TRANSSM`,`DT_TRANSRM`,`DT_TRANSRS`,`DT_TRANSSE`,`NU_LOTE_V`,`NU_LOTE_H`,`CS_FLXRET`,`FLXRECEBI`,`IDENT_MICR`,`MIGRADO_W`,`DT_INVEST`,`ID_OCUPA_N`,`ANT_SENTIN`,`FC_CONTATO`,
  `OUT_CONTAT`,`NM_CONTATO`,`END_CONTAT`,`CS_VAC_N`,`DT_ULT_DOS`,`DT_CATARRA`,`CS_TOSSE_E`,`CS_TOSSE_P`,`CS_CRISE`,`CS_CIANOSE`,`CS_VOMITOS`,`CS_APNEIA`,`CS_TEMP37`,`CS_TEMP_38`,`CS_OUT_SIN`,`NM_OUT_SIN`,`CS_PNEUMON`,`CS_ENCEFAL`,`CS_DESITRA`,`CS_OTITE`,`CS_DESNUTR`,`CS_OUT_COM`,`NM_OUT_COM`,`CS_HOSPITA`,`DT_INTERNA`,`COD_UF_HOS`,`COD_MUN_HO`,`COD_HOSP`,`CS_ANTIBIO`,`DT_ADM_ANT`,`CS_COLETA`,`DT_COLETA`,`CS_CULTURA`,`MED_IDEN_C`,`MED_QUAN_C`,`MED_CASO_S`,`COLET_COMU`,`QUAN_COMUN`,`QUAN_POSIT`,`MED_BLOQUE`,`CLASSI_FIN`,`CRITERIO`,`DOENCA_TRA`,`EVOLUCAO`,`DT_OBITO`,`DT_ENCERRA`,`NU_LOTE_I`);

  -- Criando a tabela famarnet
    CREATE TABLE `famarnet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(44) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(21) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(41) DEFAULT NULL,`SG_UF` varchar(2) DEFAULT NULL,`ID_MN_RESI` varchar(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(30) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(6) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(40) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(3) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_INFO_1` varchar(10) DEFAULT NULL,`DT_INFO_2` varchar(10) DEFAULT NULL,`DT_INFO_3` varchar(10) DEFAULT NULL,`CO_UF_OBS1` varchar(2) DEFAULT NULL,`CO_UF_OBS2` varchar(2) DEFAULT NULL,`CO_UF_OBS3` varchar(2) DEFAULT NULL,`CO_MUN_1` varchar(6) DEFAULT NULL,`CO_MUN_2` varchar(6) DEFAULT NULL,`CO_MUN_3` varchar(6) DEFAULT NULL,`CO_PAIS_1` varchar(2) DEFAULT NULL,`CO_PAIS_2` varchar(1) DEFAULT NULL,`CO_PAIS_3` varchar(1) DEFAULT NULL,`DS_TRANS_1` varchar(30) DEFAULT NULL,`DS_TRANS_2` varchar(30) DEFAULT NULL,`DS_TRANS_3` varchar(15) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`EPIZOOTIAS` varchar(1) DEFAULT NULL,`ISOL_VIR_N` varchar(1) DEFAULT NULL,`VETOR_A` varchar(1) DEFAULT NULL,`VACINADO` varchar(1) DEFAULT NULL,`DT_VACINA` varchar(10) DEFAULT NULL,`UF_VAC` varchar(2) DEFAULT NULL,`MUNCI_VAC` varchar(6) DEFAULT NULL,`UNID_VAC` varchar(7) DEFAULT NULL,`DOR_ABDO_N` varchar(1) DEFAULT NULL,`SINT_HEM_N` varchar(1) DEFAULT NULL,`FAGET` varchar(1) DEFAULT NULL,`EXCR_RENA_` varchar(1) DEFAULT NULL,`HOSPITALIZ` varchar(1) DEFAULT NULL,`DT_INTERNA` varchar(10) DEFAULT NULL,`UF` varchar(2) DEFAULT NULL,`MUNICIPIO` varchar(6) DEFAULT NULL,`HOSPITAL` varchar(7) DEFAULT NULL,`BT` varchar(5) DEFAULT NULL,`AST` varchar(5) DEFAULT NULL,`BD` varchar(5) DEFAULT NULL,`ALT` varchar(5) DEFAULT NULL,`DT_COL_1` varchar(10) DEFAULT NULL,`S1_IGM` varchar(1) DEFAULT NULL,`DT_COL_2` varchar(10) DEFAULT NULL,`S2_IGM` varchar(1) DEFAULT NULL,`MAT_COLETA` varchar(1) DEFAULT NULL,`DT_COLETA` varchar(10) DEFAULT NULL,`RES_ISOLAM` varchar(1) DEFAULT NULL,`HISTOPA` varchar(1) DEFAULT NULL,`IMUNOH` varchar(1) DEFAULT NULL,`DT_PTPCR` varchar(10) DEFAULT NULL,`RES_PTPCR` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CLASFIN_ES` varchar(30) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(29) DEFAULT NULL,`LOCALIDADE` varchar(43) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`CON_ATIVID` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,`DS_OBS` varchar(254) DEFAULT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  -- Inserindo chave primária na tabela famarnet
  ALTER TABLE `famarnet` ADD PRIMARY KEY (`NU_NOTIFIC`);

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/FAMARNET.csv'
  INTO TABLE `famarnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
  (`NU_NOTIFIC`,`TP_NOT`,`ID_AGRAVO`,`DT_NOTIFIC`,`SEM_NOT`,`NU_ANO`,`SG_UF_NOT`,`ID_MUNICIP`,`ID_REGIONA`,`ID_UNIDADE`,`DT_SIN_PRI`,`SEM_PRI`,`NM_PACIENT`,`DT_NASC`,`FONETICA_N`,`SOUNDEX`,`NU_IDADE_N`,`CS_SEXO`,`CS_GESTANT`,`CS_RACA`,`CS_ESCOL_N`,`ID_CNS_SUS`,`NM_MAE_PAC`,`SG_UF`,`ID_MN_RESI`,`ID_RG_RESI`,`ID_DISTRIT`,`ID_BAIRRO`,`NM_BAIRRO`,`ID_LOGRADO`,`NM_LOGRADO`,`NU_NUMERO`,`NM_COMPLEM`,`ID_GEO1`,`ID_GEO2`,`NM_REFEREN`,`NU_CEP`,`NU_DDD_TEL`,`NU_TELEFON`,`CS_ZONA`,`ID_PAIS`,`NDUPLIC_N`,`DT_DIGITA`,`DT_INFO_1`,`DT_INFO_2`,`DT_INFO_3`,`CO_UF_OBS1`,`CO_UF_OBS2`,`CO_UF_OBS3`,`CO_MUN_1`,`CO_MUN_2`,`CO_MUN_3`,`CO_PAIS_1`,`CO_PAIS_2`,`CO_PAIS_3`,`DS_TRANS_1`,`DS_TRANS_2`,`DS_TRANS_3`,`DT_TRANSUS`,`DT_TRANSDM`,`DT_TRANSSM`,`DT_TRANSRM`,`DT_TRANSRS`,`DT_TRANSSE`,`NU_LOTE_V`,`NU_LOTE_H`,`CS_FLXRET`,`FLXRECEBI`,`IDENT_MICR`,`MIGRADO_W`,`DT_INVEST`,`ID_OCUPA_N`,`EPIZOOTIAS`,`ISOL_VIR_N`,`VETOR_A`,`VACINADO`,`DT_VACINA`,`UF_VAC`,`MUNCI_VAC`,`UNID_VAC`,`DOR_ABDO_N`,`SINT_HEM_N`,`FAGET`,`EXCR_RENA_`,`HOSPITALIZ`,`DT_INTERNA`,`UF`,`MUNICIPIO`,
  `HOSPITAL`,`BT`,`AST`,`BD`,`ALT`,`DT_COL_1`,`S1_IGM`,`DT_COL_2`,`S2_IGM`,`MAT_COLETA`,`DT_COLETA`,`RES_ISOLAM`,`HISTOPA`,`IMUNOH`,`DT_PTPCR`,`RES_PTPCR`,`CLASSI_FIN`,`CLASFIN_ES`,`CRITERIO`,`TPAUTOCTO`,`COUFINF`,`COPAISINF`,`COMUNINF`,`CODISINF`,`CO_BAINFC`,`NOBAIINF`,`LOCALIDADE`,`DOENCA_TRA`,`CON_ATIVID`,`EVOLUCAO`,`DT_OBITO`,`DT_ENCERRA`,`NU_LOTE_I`);

  -- Criando a tabela leptonet --
  CREATE TABLE `leptonet` (`NU_NOTIFIC` int(7) NOT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(4) DEFAULT NULL,`DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,`ID_REGIONA` varchar(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(46) DEFAULT NULL,`DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(21) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,`CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` varchar(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(11) DEFAULT NULL,`NM_MAE_PAC` varchar(43) DEFAULT NULL,`SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` varchar(4) DEFAULT NULL,`ID_DISTRIT` varchar(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,`NM_BAIRRO` varchar(30) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(59) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(30) DEFAULT NULL,`NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,`NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,`DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,`CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(11) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,`ID_OCUPA_N` varchar(6) DEFAULT NULL,`ANT_CB_LAM` varchar(1) DEFAULT NULL,`ANT_CB_CRI` varchar(1) DEFAULT NULL,`ANT_CB_CAI` varchar(1) DEFAULT NULL,`ANT_CB_FOS` varchar(1) DEFAULT NULL,`ANT_CB_SIN` varchar(1) DEFAULT NULL,`ANT_CB_PLA` varchar(1) DEFAULT NULL,`ANT_CB_COR` varchar(1) DEFAULT NULL,`ANT_CB_ROE` varchar(1) DEFAULT NULL,`ANT_CB_GRA` varchar(1) DEFAULT NULL,`ANT_CB_TER` varchar(1) DEFAULT NULL,`ANT_CB_LIX` varchar(1) DEFAULT NULL,`ANT_CB_OUT` varchar(1) DEFAULT NULL,`ANT_OU_DES` varchar(30) DEFAULT NULL,`ANT_HUMANO` varchar(1) DEFAULT NULL,`ANT_ANIMAI` varchar(1) DEFAULT NULL,`CLI_DT_ATE` varchar(10) DEFAULT NULL,`CLI_FEBRE` varchar(1) DEFAULT NULL,`CLI_MIALGI` varchar(1) DEFAULT NULL,`CLI_CEFALE` varchar(1) DEFAULT NULL,`CLI_PROST` varchar(1) DEFAULT NULL,`CLI_CONGES` varchar(1) DEFAULT NULL,`CLI_PANTUR` varchar(1) DEFAULT NULL,`CLI_VOMITO` varchar(1) DEFAULT NULL,`CLI_DIARRE` varchar(1) DEFAULT NULL,`CLI_ICTERI` varchar(1) DEFAULT NULL,`CLI_RENAL` varchar(1) DEFAULT NULL,`CLI_RESPIR` varchar(1) DEFAULT NULL,`CLI_CARDIA` varchar(1) DEFAULT NULL,`CLI_HEMOPU` varchar(1) DEFAULT NULL,`CLI_HEMORR` varchar(1) DEFAULT NULL,`CLI_MENING` varchar(1) DEFAULT NULL,`CLI_OUTROS` varchar(1) DEFAULT NULL,`CLI_OTRDES` varchar(30) DEFAULT NULL,`ATE_HOSP` varchar(1) DEFAULT NULL,`ATE_DT_INT` varchar(10) DEFAULT NULL,`ATE_DT_ALT` varchar(10) DEFAULT NULL,`ATE_UF` varchar(2) DEFAULT NULL,`ATE_MUNICI` varchar(6) DEFAULT NULL,`ATE_HOSPIT` varchar(7) DEFAULT NULL,`LAB_DT_1` varchar(10) DEFAULT NULL,`LAB_ELIS_1` varchar(1) DEFAULT NULL,`LAB_DT_2` varchar(10) DEFAULT NULL,`LAB_ELIS_2` varchar(1) DEFAULT NULL,`DTMICRO1` varchar(10) DEFAULT NULL,`MICRO1_S1` varchar(30) DEFAULT NULL,`MICRO1_T_1` varchar(4) DEFAULT NULL,`MICRO1_S_2` varchar(30) DEFAULT NULL,`MICRO1_T_2` varchar(5) DEFAULT NULL,`LAB_MICR_1` varchar(1) DEFAULT NULL,`DTMICRO2` varchar(10) DEFAULT NULL,`MICRO2_S1` varchar(30) DEFAULT NULL,`MICRO2_T_1` varchar(4) DEFAULT NULL,`MICRO2_S_2` varchar(30) DEFAULT NULL,`MICRO2_T_2` varchar(4) DEFAULT NULL,`LAB_MICR_2` varchar(1) DEFAULT NULL,`DTISOLA` varchar(10) DEFAULT NULL,`RES_ISOL` varchar(1) DEFAULT NULL,`DTIMUNO` varchar(10) DEFAULT NULL,`RES_IMUNO` varchar(1) DEFAULT NULL,`DT_PCR` varchar(10) DEFAULT NULL,`RES_PCR` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,`COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,`NOBAIINF` varchar(10) DEFAULT NULL,`CON_AREA` varchar(1) DEFAULT NULL,`CON_AMBIEN` varchar(1) DEFAULT NULL,`DOENCA_TRA` varchar(1) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`DT_RISCO1` varchar(10) DEFAULT NULL,`DT_RISCO2` varchar(10) DEFAULT NULL,`DT_RISCO3` varchar(10) DEFAULT NULL,`DT_RISCO4` varchar(10) DEFAULT NULL,`CO_MUN_R1` varchar(6) DEFAULT NULL,`CO_MUN_R2` varchar(6) DEFAULT NULL,`CO_MUN_R3` varchar(10) DEFAULT NULL,`CO_MUN_R4` varchar(10) DEFAULT NULL,`CO_UF_R1` varchar(2) DEFAULT NULL,`CO_UF_R2` varchar(2) DEFAULT NULL,`CO_UF_R3` varchar(10) DEFAULT NULL,`CO_UF_R4` varchar(10) DEFAULT NULL,`NO_END_R1` varchar(30) DEFAULT NULL,`NO_END_R2` varchar(39) DEFAULT NULL,`NO_END_R3` varchar(10) DEFAULT NULL,`NO_END_R4` varchar(10) DEFAULT NULL,`NO_LOC_R1` varchar(30) DEFAULT NULL,`NO_LOC_R2` varchar(19) DEFAULT NULL,`NO_LOC_R3` varchar(10) DEFAULT NULL,`NO_LOC_R4` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,`DS_OBS` varchar(254) DEFAULT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  -- Inserindo chave primária
  ALTER TABLE `leptonet`ADD PRIMARY KEY (`NU_NOTIFIC`);

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/LEPTONET.csv'
  INTO TABLE `leptonet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
  (`NU_NOTIFIC`,`TP_NOT`,`ID_AGRAVO`,`DT_NOTIFIC`,`SEM_NOT`,`NU_ANO`,`SG_UF_NOT`,`ID_MUNICIP`,`ID_REGIONA`,`ID_UNIDADE`,`DT_SIN_PRI`,`SEM_PRI`,`NM_PACIENT`,`DT_NASC`,`FONETICA_N`,`SOUNDEX`,`NU_IDADE_N`,`CS_SEXO`,`CS_GESTANT`,`CS_RACA`,`CS_ESCOL_N`,`ID_CNS_SUS`,`NM_MAE_PAC`,`SG_UF`,`ID_MN_RESI`,`ID_RG_RESI`,`ID_DISTRIT`,`ID_BAIRRO`,`NM_BAIRRO`,`ID_LOGRADO`,`NM_LOGRADO`,`NU_NUMERO`,`NM_COMPLEM`,`ID_GEO1`,`ID_GEO2`,`NM_REFEREN`,`NU_CEP`,`NU_DDD_TEL`,`NU_TELEFON`,`CS_ZONA`,`ID_PAIS`,`NDUPLIC_N`,`DT_DIGITA`,`DT_TRANSUS`,`DT_TRANSDM`,`DT_TRANSSM`,`DT_TRANSRM`,`DT_TRANSRS`,`DT_TRANSSE`,`NU_LOTE_V`,`NU_LOTE_H`,`CS_FLXRET`,`FLXRECEBI`,`IDENT_MICR`,`MIGRADO_W`,`DT_INVEST`,`ID_OCUPA_N`,`ANT_CB_LAM`,`ANT_CB_CRI`,`ANT_CB_CAI`,`ANT_CB_FOS`,`ANT_CB_SIN`,`ANT_CB_PLA`,`ANT_CB_COR`,`ANT_CB_ROE`,`ANT_CB_GRA`,`ANT_CB_TER`,`ANT_CB_LIX`,`ANT_CB_OUT`,`ANT_OU_DES`,`ANT_HUMANO`,`ANT_ANIMAI`,`CLI_DT_ATE`,`CLI_FEBRE`,`CLI_MIALGI`,`CLI_CEFALE`,`CLI_PROST`,`CLI_CONGES`,
  `CLI_PANTUR`,`CLI_VOMITO`,`CLI_DIARRE`,`CLI_ICTERI`,`CLI_RENAL`,`CLI_RESPIR`,`CLI_CARDIA`,`CLI_HEMOPU`,`CLI_HEMORR`,`CLI_MENING`,`CLI_OUTROS`,`CLI_OTRDES`,`ATE_HOSP`,`ATE_DT_INT`,`ATE_DT_ALT`,`ATE_UF`,`ATE_MUNICI`,`ATE_HOSPIT`,`LAB_DT_1`,`LAB_ELIS_1`,`LAB_DT_2`,`LAB_ELIS_2`,`DTMICRO1`,`MICRO1_S1`,`MICRO1_T_1`,`MICRO1_S_2`,`MICRO1_T_2`,`LAB_MICR_1`,`DTMICRO2`,`MICRO2_S1`,`MICRO2_T_1`,`MICRO2_S_2`,`MICRO2_T_2`,`LAB_MICR_2`,`DTISOLA`,`RES_ISOL`,`DTIMUNO`,`RES_IMUNO`,`DT_PCR`,`RES_PCR`,`CLASSI_FIN`,`CRITERIO`,`TPAUTOCTO`,`COUFINF`,`COPAISINF`,`COMUNINF`,`CODISINF`,`CO_BAINFC`,`NOBAIINF`,`CON_AREA`,`CON_AMBIEN`,`DOENCA_TRA`,`EVOLUCAO`,`DT_OBITO`,`DT_ENCERRA`,`DT_RISCO1`,`DT_RISCO2`,`DT_RISCO3`,`DT_RISCO4`,`CO_MUN_R1`,`CO_MUN_R2`,`CO_MUN_R3`,`CO_MUN_R4`,`CO_UF_R1`,`CO_UF_R2`,`CO_UF_R3`,`CO_UF_R4`,`NO_END_R1`,`NO_END_R2`,`NO_END_R3`,`NO_END_R4`,`NO_LOC_R1`,`NO_LOC_R2`,`NO_LOC_R3`,`NO_LOC_R4`,`NU_LOTE_I`,`DS_OBS`);

  -- Criando a tabela exantnet --
  CREATE TABLE `exantnet` (`NU_NOTIFIC` int(7) DEFAULT NULL,`TP_NOT` int(1) DEFAULT NULL,`ID_AGRAVO` varchar(3) DEFAULT NULL,`CS_SUSPEIT` int(1) DEFAULT NULL,
  `DT_NOTIFIC` varchar(10) DEFAULT NULL,`SEM_NOT` int(6) DEFAULT NULL,`NU_ANO` int(4) DEFAULT NULL,`SG_UF_NOT` int(2) DEFAULT NULL,`ID_MUNICIP` int(6) DEFAULT NULL,
  `ID_REGIONA` int(4) DEFAULT NULL,`ID_UNIDADE` int(7) DEFAULT NULL,`DT_SIN_PRI` varchar(10) DEFAULT NULL,`SEM_PRI` int(6) DEFAULT NULL,`NM_PACIENT` varchar(35) DEFAULT NULL,
  `DT_NASC` varchar(10) DEFAULT NULL,`FONETICA_N` varchar(18) DEFAULT NULL,`SOUNDEX` varchar(15) DEFAULT NULL,`NU_IDADE_N` int(4) DEFAULT NULL,`CS_SEXO` varchar(1) DEFAULT NULL,
  `CS_GESTANT` int(1) DEFAULT NULL,`CS_RACA` int(1) DEFAULT NULL,`CS_ESCOL_N` varchar(2) DEFAULT NULL,`ID_CNS_SUS` varchar(15) DEFAULT NULL,`NM_MAE_PAC` varchar(38) DEFAULT NULL,
  `SG_UF` int(2) DEFAULT NULL,`ID_MN_RESI` int(6) DEFAULT NULL,`ID_RG_RESI` int(4) DEFAULT NULL,`ID_DISTRIT` int(2) DEFAULT NULL,`ID_BAIRRO` varchar(2) DEFAULT NULL,
  `NM_BAIRRO` varchar(9) DEFAULT NULL,`ID_LOGRADO` varchar(5) DEFAULT NULL,`NM_LOGRADO` varchar(56) DEFAULT NULL,`NU_NUMERO` varchar(5) DEFAULT NULL,`NM_COMPLEM` varchar(30) DEFAULT NULL,
  `NM_CONTATO` varchar(40) DEFAULT NULL,`END_CONTAT` varchar(39) DEFAULT NULL,`ID_GEO1` varchar(10) DEFAULT NULL,`ID_GEO2` varchar(10) DEFAULT NULL,`NM_REFEREN` varchar(16) DEFAULT NULL,
  `NU_CEP` varchar(8) DEFAULT NULL,`NU_DDD_TEL` varchar(2) DEFAULT NULL,`NU_TELEFON` varchar(9) DEFAULT NULL,`CS_ZONA` varchar(1) DEFAULT NULL,`ID_PAIS` int(1) DEFAULT NULL,
  `NDUPLIC_N` varchar(10) DEFAULT NULL,`DT_DIGITA` varchar(10) DEFAULT NULL,`DT_TRANSUS` varchar(10) DEFAULT NULL,`DT_TRANSDM` varchar(10) DEFAULT NULL,`DT_TRANSSM` varchar(10) DEFAULT NULL,
  `DT_TRANSRM` varchar(10) DEFAULT NULL,`DT_TRANSRS` varchar(10) DEFAULT NULL,`DT_TRANSSE` varchar(10) DEFAULT NULL,`NU_LOTE_V` varchar(7) DEFAULT NULL,`NU_LOTE_H` varchar(10) DEFAULT NULL,
  `CS_FLXRET` varchar(10) DEFAULT NULL,`FLXRECEBI` varchar(10) DEFAULT NULL,`IDENT_MICR` bigint(13) DEFAULT NULL,`MIGRADO_W` varchar(10) DEFAULT NULL,`DT_INVEST` varchar(10) DEFAULT NULL,
  `ID_OCUPA_N` varchar(6) DEFAULT NULL,`CS_VACINA` int(1) DEFAULT NULL,`DT_DOSE_N` varchar(10) DEFAULT NULL,`CS_FONTE` int(1) DEFAULT NULL,`NM_FONTE` varchar(10) DEFAULT NULL,
  `END_FONTE` varchar(10) DEFAULT NULL,`DT_INICIO_` varchar(10) DEFAULT NULL,`DT_FEBRE` varchar(10) DEFAULT NULL,`ID_TOSSE` int(1) DEFAULT NULL,`ID_CORIZA` varchar(1) DEFAULT NULL,
  `ID_CONJUNT` varchar(1) DEFAULT NULL,`ID_ARTRALG` varchar(1) DEFAULT NULL,`ID_GANGLIO` varchar(1) DEFAULT NULL,`ID_RETRO` varchar(1) DEFAULT NULL,`ID_HOSPIT` int(1) DEFAULT NULL,
  `DT_INTERNA` varchar(10) DEFAULT NULL,`UF_H` varchar(2) DEFAULT NULL,`NM_MUN_HOS` varchar(6) DEFAULT NULL,`NM_HOSPITA` varchar(7) DEFAULT NULL,`DT_COL_1` varchar(10) DEFAULT NULL,
  `DT_COL_2` varchar(10) DEFAULT NULL,`ID_S1_IGM` varchar(1) DEFAULT NULL,`ID_S1_IGG` varchar(1) DEFAULT NULL,`ID_S1_IGM_` varchar(1) DEFAULT NULL,`ID_S1_IGG_` varchar(1) DEFAULT NULL,
  `ID_S1_IG_1` varchar(1) DEFAULT NULL,`ID_S1_IG_2` varchar(1) DEFAULT NULL,`ID_S2_IGM` varchar(10) DEFAULT NULL,`ID_S2_IGG` varchar(10) DEFAULT NULL,`ID_S2_IGM_` varchar(10) DEFAULT NULL,
  `ID_S2_IGG_` varchar(10) DEFAULT NULL,`ID_S2_IG_1` varchar(10) DEFAULT NULL,`ID_S2_IG_2` varchar(10) DEFAULT NULL,`ID_RE_IGM` varchar(10) DEFAULT NULL,`ID_RE_IGG` varchar(10) DEFAULT NULL,
  `ID_RE_IGM_` varchar(10) DEFAULT NULL,`ID_RE_IGG_` varchar(10) DEFAULT NULL,`ID_RE_IG_1` varchar(10) DEFAULT NULL,`ID_RE_IG_2` varchar(10) DEFAULT NULL,`TPEXANTE` varchar(10) DEFAULT NULL,
  `ID_SANGUE` varchar(1) DEFAULT NULL,`ID_URINA` varchar(1) DEFAULT NULL,`ID_SECRECA` varchar(1) DEFAULT NULL,`ID_LIQUOR` varchar(1) DEFAULT NULL,`ID_ETIOLOG` varchar(1) DEFAULT NULL,
  `ETIOL_OUTR` varchar(10) DEFAULT NULL,`CS_VACINAL` varchar(1) DEFAULT NULL,`MENOR_5ANO` varchar(1) DEFAULT NULL,`DE5A14ANOS` varchar(3) DEFAULT NULL,`DE15A39ANO` varchar(3) DEFAULT NULL,
  `INT_TEMPO` varchar(1) DEFAULT NULL,`CLASSI_FIN` varchar(1) DEFAULT NULL,`CRITERIO` varchar(1) DEFAULT NULL,`CS_DESCART` varchar(1) DEFAULT NULL,`TPAUTOCTO` varchar(1) DEFAULT NULL,
  `COUFINF` varchar(2) DEFAULT NULL,`COPAISINF` varchar(1) DEFAULT NULL,`COMUNINF` varchar(6) DEFAULT NULL,`CODISINF` varchar(2) DEFAULT NULL,`CO_BAINFC` varchar(2) DEFAULT NULL,
  `NOBAIINF` varchar(8) DEFAULT NULL,`EVOLUCAO` varchar(1) DEFAULT NULL,`DT_OBITO` varchar(10) DEFAULT NULL,`DT_ENCERRA` varchar(10) DEFAULT NULL,`NU_LOTE_I` varchar(7) DEFAULT NULL,
  `DT_DESC1` varchar(10) DEFAULT NULL,`DT_DESC2` varchar(10) DEFAULT NULL,`DT_DESC3` varchar(10) DEFAULT NULL,`CO_UF_DES1` varchar(2) DEFAULT NULL,`CO_UF_DES2` varchar(2) DEFAULT NULL,
  `CO_UF_DES3` varchar(2) DEFAULT NULL,`MUN_DES1` varchar(6) DEFAULT NULL,`MUN_DES2` varchar(6) DEFAULT NULL,`MUN_DES3` varchar(6) DEFAULT NULL,`PA_DES1` varchar(3) DEFAULT NULL,
  `PA_DES2` varchar(2) DEFAULT NULL,`PA_DES3` varchar(1) DEFAULT NULL,`DS_TRANS1` varchar(5) DEFAULT NULL,`DS_TRANS2` varchar(5) DEFAULT NULL,`DS_TRANS3` varchar(5) DEFAULT NULL,
  `DS_OBS` varchar(254) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    -- Inserindo chave primária
  -- ALTER TABLE `exantnet`ADD PRIMARY KEY (`NU_NOTIFIC`);
  -- Inserindo o campo id na tabela
  ALTER TABLE `exantnet` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

  -- Carregando os dados do excel csv da pasta abaixo ...
  LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/EXANTNET.csv'
  INTO TABLE `exantnet` CHARACTER SET latin1 FIELDS TERMINATED BY ';' IGNORE 1 ROWS
    (`NU_NOTIFIC`, `TP_NOT`, `ID_AGRAVO`, `CS_SUSPEIT`, `DT_NOTIFIC`, `SEM_NOT`, `NU_ANO`, `SG_UF_NOT`, `ID_MUNICIP`, `ID_REGIONA`, `ID_UNIDADE`, `DT_SIN_PRI`, `SEM_PRI`, `NM_PACIENT`, `DT_NASC`, `FONETICA_N`, `SOUNDEX`, `NU_IDADE_N`, `CS_SEXO`, `CS_GESTANT`, `CS_RACA`, `CS_ESCOL_N`, `ID_CNS_SUS`, `NM_MAE_PAC`, `SG_UF`, `ID_MN_RESI`, `ID_RG_RESI`, `ID_DISTRIT`, `ID_BAIRRO`, `NM_BAIRRO`, `ID_LOGRADO`, `NM_LOGRADO`, `NU_NUMERO`, `NM_COMPLEM`, `NM_CONTATO`, `END_CONTAT`, `ID_GEO1`, `ID_GEO2`, `NM_REFEREN`, `NU_CEP`, `NU_DDD_TEL`, `NU_TELEFON`, `CS_ZONA`, `ID_PAIS`, `NDUPLIC_N`, `DT_DIGITA`, `DT_TRANSUS`, `DT_TRANSDM`, `DT_TRANSSM`, `DT_TRANSRM`, `DT_TRANSRS`, `DT_TRANSSE`, `NU_LOTE_V`, `NU_LOTE_H`, `CS_FLXRET`, `FLXRECEBI`, `IDENT_MICR`, `MIGRADO_W`, `DT_INVEST`, `ID_OCUPA_N`, `CS_VACINA`, `DT_DOSE_N`, `CS_FONTE`, `NM_FONTE`, `END_FONTE`, `DT_INICIO_`, `DT_FEBRE`, `ID_TOSSE`, `ID_CORIZA`, `ID_CONJUNT`, `ID_ARTRALG`, `ID_GANGLIO`, `ID_RETRO`, `ID_HOSPIT`, `DT_INTERNA`, `UF_H`, `NM_MUN_HOS`, `NM_HOSPITA`, `DT_COL_1`, `DT_COL_2`, `ID_S1_IGM`, `ID_S1_IGG`, `ID_S1_IGM_`, `ID_S1_IGG_`, `ID_S1_IG_1`, `ID_S1_IG_2`, `ID_S2_IGM`, `ID_S2_IGG`, `ID_S2_IGM_`, `ID_S2_IGG_`, `ID_S2_IG_1`, `ID_S2_IG_2`, `ID_RE_IGM`, `ID_RE_IGG`, `ID_RE_IGM_`, `ID_RE_IGG_`, `ID_RE_IG_1`, `ID_RE_IG_2`, `TPEXANTE`, `ID_SANGUE`, `ID_URINA`, `ID_SECRECA`, `ID_LIQUOR`, `ID_ETIOLOG`, `ETIOL_OUTR`, `CS_VACINAL`, `MENOR_5ANO`, `DE5A14ANOS`, `DE15A39ANO`, `INT_TEMPO`, `CLASSI_FIN`, `CRITERIO`, `CS_DESCART`, `TPAUTOCTO`, `COUFINF`, `COPAISINF`, `COMUNINF`, `CODISINF`, `CO_BAINFC`, `NOBAIINF`, `EVOLUCAO`, `DT_OBITO`, `DT_ENCERRA`, `NU_LOTE_I`, `DT_DESC1`, `DT_DESC2`, `DT_DESC3`, `CO_UF_DES1`, `CO_UF_DES2`, `CO_UF_DES3`, `MUN_DES1`, `MUN_DES2`, `MUN_DES3`, `PA_DES1`, `PA_DES2`, `PA_DES3`, `DS_TRANS1`, `DS_TRANS2`, `DS_TRANS3`, `DS_OBS`);

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `chiku_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `chiku_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `chiku_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataChiku.csv'
INTO TABLE `chiku_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`,`Paciente`,`CNS`,`Setor`,`Bancada`,`Mun. Residência`,`UF Residência`,`Requisitante`,`Mun. Requisitante`,`Exame`,`Metodo`,`Material`,`Cód. Amostra`,`Amostra`,
`Restrição`,`Labotório Cadastro`,`Dt. Cadastro`,`Dt. Recebimento`,`Dt. Liberação`,`Tempo Liberação`,`Labotório Executor`,`Status Exame`,`Resultado`);

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `febrea_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `febrea_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `febrea_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataFebre.csv'
INTO TABLE `febrea_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`,`Paciente`,`CNS`,`Setor`,`Bancada`,`Mun. Residência`,`UF Residência`,`Requisitante`,`Mun. Requisitante`,`Exame`,`Metodo`,`Material`,`Cód. Amostra`,`Amostra`,
`Restrição`,`Labotório Cadastro`,`Dt. Cadastro`,`Dt. Recebimento`,`Dt. Liberação`,`Tempo Liberação`,`Labotório Executor`,`Status Exame`,`Resultado`);


-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `coque_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `coque_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `coque_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataCoque.csv'
INTO TABLE `coque_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`,`Paciente`,`CNS`,`Setor`,`Bancada`,`Mun. Residência`,`UF Residência`,`Requisitante`,`Mun. Requisitante`,`Exame`,`Metodo`,`Material`,`Cód. Amostra`,`Amostra`,
`Restrição`,`Labotório Cadastro`,`Dt. Cadastro`,`Dt. Recebimento`,`Dt. Liberação`,`Tempo Liberação`,`Labotório Executor`,`Status Exame`,`Resultado`);

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `dengue_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `dengue_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `dengue_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Inserindo os dados na tabela criada no script acima ...
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataDengue.csv'
INTO TABLE `dengue_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`,`Paciente`,`CNS`,`Setor`,`Bancada`,`Mun. Residência`,`UF Residência`,`Requisitante`,`Mun. Requisitante`,`Exame`,`Metodo`,`Material`,`Cód. Amostra`,`Amostra`,
`Restrição`,`Labotório Cadastro`,`Dt. Cadastro`,`Dt. Recebimento`,`Dt. Liberação`,`Tempo Liberação`,`Labotório Executor`,`Status Exame`,`Resultado`);


-- Requisição, Laboratório de Cadastro, Unidade Solicitante, Municipio do Solicitante, Núm. Notificação Sinan, CNS do Paciente, Paciente, Municipio de Residência, Estado de Residência, Exame, Metodologia, Data de Cadastro, Material Biológico, Amostra, Data do Recebimento, Laboratório Executor, Data da Liberação, Status Exame, 1º Campo Resultado
-- Exames: Dengue , IgM - Sorologia	Enzimaimunoensaio,Dengue, Biologia Molecular	PCR em Tempo Real,Dengue, Detecção de Antígeno NS1	Enzimaimunoensaio,Dengue, IgM	Enzimaimunoensaio,Dengue, Isolamento Viral	Isolamento Viral

-- Exames: Dengue , IgM - Sorologia	Enzimaimunoensaio , Dengue, Biologia Molecular	PCR em Tempo Real, Dengue , Detecção de Antígeno NS1	Enzimaimunoensaio,
-- Dengue, IgM	Enzimaimunoensaio , Dengue, Isolamento Viral	Isolamento Viral

-- Requisição, Unidade Solicitante, Municipio do Solicitante, CNS do Paciente, Paciente, Municipio de Residência, Estado de Residência, Exame, Metodologia, Data de Cadastro, Material Clínico, Amostra, Data do Recebimento, Data da Liberação, Status Exame, 1º Campo Resultado

-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `zika_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(43) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(7) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(22) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(9) DEFAULT NULL,`Exame` varchar(33) DEFAULT NULL,`Metodo` varchar(21) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(6) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,`Dt. Cadastro` varchar(16) DEFAULT NULL,
  `Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,`Labotório Executor` varchar(29) DEFAULT NULL,
  `Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(22) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `zika_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `zika_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataZika.csv'
INTO TABLE `zika_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`,`Paciente`,`CNS`,`Setor`,`Bancada`,`Mun. Residência`,`UF Residência`,`Requisitante`,`Mun. Requisitante`,`Exame`,`Metodo`,`Material`,`Cód. Amostra`,`Amostra`,
`Restrição`,`Labotório Cadastro`,`Dt. Cadastro`,`Dt. Recebimento`,`Dt. Liberação`,`Tempo Liberação`,`Labotório Executor`,`Status Exame`,`Resultado`);


-- IAL disponivel em https://gal.saude.sp.gov.br/gal/login/ => Usuário: 4050339.ve Senha: suvisjacana Módulo: Biologia Medica Laboratorio: Sao Paulo
-- menu => consultas => Consultar Exame => Digitar a Data Inicio, Data Fim, Exame e clicar em filtrar para gerar tabela, em seguida clique no botao de excel
CREATE TABLE `sarampo_ial` (`Requisição` bigint(12) DEFAULT NULL,`Paciente` varchar(48) DEFAULT NULL,`CNS` varchar(15) DEFAULT NULL,`Setor` varchar(6) DEFAULT NULL,
  `Bancada` varchar(9) DEFAULT NULL,`Mun. Residência` varchar(21) DEFAULT NULL,`UF Residência` varchar(2) DEFAULT NULL,`Requisitante` varchar(60) DEFAULT NULL,
  `Mun. Requisitante` varchar(20) DEFAULT NULL,`Exame` varchar(27) DEFAULT NULL,`Metodo` varchar(36) DEFAULT NULL,`Material` varchar(33) DEFAULT NULL,
  `Cód. Amostra` int(7) DEFAULT NULL,`Amostra` int(1) DEFAULT NULL,`Restrição` varchar(10) DEFAULT NULL,`Labotório Cadastro` varchar(32) DEFAULT NULL,
  `Dt. Cadastro` varchar(16) DEFAULT NULL,`Dt. Recebimento` varchar(16) DEFAULT NULL,`Dt. Liberação` varchar(16) DEFAULT NULL,`Tempo Liberação` varchar(3) DEFAULT NULL,
  `Labotório Executor` varchar(29) DEFAULT NULL,`Status Exame` varchar(26) DEFAULT NULL,`Resultado` varchar(15) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ALTER TABLE `sarampo_ial`ADD PRIMARY KEY (`Requisição`);
-- Inserindo o campo id na tabela
ALTER TABLE `sarampo_ial` ADD `id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

-- Exportando novos resultados do ial sarampo
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/dataSarampo.csv'
INTO TABLE `sarampo_ial`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`Requisição`, `Paciente`, `CNS`, `Setor`, `Bancada`, `Mun. Residência`, `UF Residência`, `Requisitante`, `Mun. Requisitante`, `Exame`, `Metodo`, `Material`, `Cód. Amostra`,
 `Amostra`, `Restrição`, `Labotório Cadastro`, `Dt. Cadastro`, `Dt. Recebimento`, `Dt. Liberação`, `Tempo Liberação`, `Labotório Executor`, `Status Exame`, `Resultado`);

-- Criando a tabela resultado_ccz
CREATE TABLE `resultado_ccz` (`ENTRADA` varchar(10) DEFAULT NULL,`PEDIDO` int(8) DEFAULT NULL,`UNIDADE_DE_SAUDE` varchar(30) DEFAULT NULL,`D_A` varchar(17) DEFAULT NULL,
  `SUVIS` varchar(30) DEFAULT NULL,`SINAN` varchar(8) DEFAULT NULL,`PACIENTE` varchar(50) DEFAULT NULL,`SEXO` varchar(1) DEFAULT NULL,`NASCIMENTO` varchar(10) DEFAULT NULL,
  `Sintoma` varchar(16) DEFAULT NULL,`Coleta` varchar(16) DEFAULT NULL,`Nr_da_Amostra` varchar(8) DEFAULT NULL,`Resultado_IgM_Panbio` varchar(17) DEFAULT NULL,
  `Kit_IgM` varchar(6) DEFAULT NULL,`Nova_Coleta_Panbio` varchar(3) DEFAULT NULL,`Resultado_IgM_Focus` varchar(17) DEFAULT NULL,`Kit_IgM1` varchar(5) DEFAULT NULL,
  `Nova_Coleta_Focus` varchar(3) DEFAULT NULL,`NS1` varchar(3) DEFAULT NULL,`Nr_AM_NS1` varchar(10) DEFAULT NULL,`Resultado_NS1` varchar(12) DEFAULT NULL,
  `Kit_NS1` varchar(6) DEFAULT NULL,`LIBERACAO_EM` varchar(10) DEFAULT NULL,`OBSERVACAO` varchar(57) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `resultado_ccz`ADD PRIMARY KEY (`PEDIDO`);

-- Exportando novos resultados do ccz dengue
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/RadGridExport.csv'
INTO TABLE `resultado_ccz`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`ENTRADA`,`PEDIDO`,`UNIDADE_DE_SAUDE`,`D_A`,`SUVIS`,`SINAN`,`PACIENTE`,`SEXO`,`NASCIMENTO`,`Sintoma`,`Coleta`,`Nr_da_Amostra`,`Resultado_IgM_Panbio`,`Kit_IgM`,`Nova_Coleta_Panbio`,`Resultado_IgM_Focus`,`Kit_IgM1`,`Nova_Coleta_Focus`,
  `NS1`,`Nr_AM_NS1`,`Resultado_NS1`,`Kit_NS1`,`LIBERACAO_EM`,`OBSERVACAO`);

DELETE FROM `resultado_ccz` WHERE `resultado_ccz`.`PEDIDO` = 11598123;
DELETE FROM `resultado_ccz` WHERE `resultado_ccz`.`PEDIDO` = 13024876;
DELETE FROM `resultado_ccz` WHERE `resultado_ccz`.`PEDIDO` = 13024906;

-- Criando a tabela resultado_ccz_lepto
CREATE TABLE `resultado_ccz_lepto` (`ENTRADA` varchar(10) DEFAULT NULL,`PEDIDO` varchar(8) DEFAULT NULL,`UNIDADE_DE_SAUDE` varchar(43) DEFAULT NULL,`D_A` varchar(21) DEFAULT NULL,
  `SUVIS` varchar(30) DEFAULT NULL,`SINAN` varchar(26) DEFAULT NULL,`PACIENTE` varchar(41) DEFAULT NULL,`SEXO` varchar(10) DEFAULT NULL,`NASCIMENTO` varchar(10) DEFAULT NULL,
  `Nr_da_Amostra` varchar(10) DEFAULT NULL,`Sintoma` varchar(13) DEFAULT NULL,`Coleta` varchar(13) DEFAULT NULL,`RES_ELISA` varchar(12) DEFAULT NULL,`CO` varchar(5) DEFAULT NULL,
  `DO` varchar(8) DEFAULT NULL,`RES_MAT` varchar(12) DEFAULT NULL,`NOVA_COLETA` varchar(19) DEFAULT NULL,`1o_SOROVAR` varchar(19) DEFAULT NULL,`1o_TIT` varchar(9) DEFAULT NULL,
  `2o_SOROVAR` varchar(13) DEFAULT NULL,`2o_TIT` varchar(9) DEFAULT NULL,`3o_SOROVAR` varchar(10) DEFAULT NULL,`3o_TIT` varchar(5) DEFAULT NULL,`4o_SOROVAR` varchar(11) DEFAULT NULL,
  `4o_TIT` varchar(9) DEFAULT NULL,`5o_SOROVAR` varchar(11) DEFAULT NULL,`5o_TIT` varchar(11) DEFAULT NULL,`6o_SOROVAR` varchar(11) DEFAULT NULL,`6o_TIT` varchar(9) DEFAULT NULL,
  `7o_SOROVAR` varchar(11) DEFAULT NULL,`7o_TIT` varchar(6) DEFAULT NULL,`8o_SOROVAR` varchar(9) DEFAULT NULL,`8o_TIT` varchar(3) DEFAULT NULL,`9o_SOROVAR` varchar(11) DEFAULT NULL,
  `9o_TIT` varchar(3) DEFAULT NULL,`10o_SOROVAR` varchar(9) DEFAULT NULL,`10o_TIT` varchar(5) DEFAULT NULL,`11o_SOROVAR` varchar(6) DEFAULT NULL,`11o_TIT` varchar(3) DEFAULT NULL,
  `12o_SOROVAR` varchar(10) DEFAULT NULL,`12o_TIT` varchar(4) DEFAULT NULL,`13_SOROVAR` varchar(9) DEFAULT NULL,`13_TIT` varchar(4) DEFAULT NULL,`14o_SOROVAR` varchar(10) DEFAULT NULL,
  `14o_TIT` varchar(10) DEFAULT NULL,`15o_SOROVAR` varchar(10) DEFAULT NULL,`15o_TIT` varchar(10) DEFAULT NULL,`16o_SOROVAR` varchar(10) DEFAULT NULL,`16o_TIT` varchar(10) DEFAULT NULL,
  `17o_SOROVAR` varchar(10) DEFAULT NULL,`17o_TIT` varchar(10) DEFAULT NULL,`18o_SOROVAR` varchar(10) DEFAULT NULL,`18o_TIT` varchar(10) DEFAULT NULL,`19o_SOROVAR` varchar(10) DEFAULT NULL,
  `19o_TIT` varchar(10) DEFAULT NULL,`LIBERACAO_EM` varchar(10) DEFAULT NULL,`OBSERVACAO` varchar(75) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `resultado_ccz_lepto`ADD PRIMARY KEY (`PEDIDO`);

-- Exportando novos resultados do ccz dengue
LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/RadGridExportLepto.csv'
INTO TABLE `resultado_ccz_lepto`
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
IGNORE 1 ROWS
(`ENTRADA`, `PEDIDO`, `UNIDADE_DE_SAUDE`, `D_A`, `SUVIS`, `SINAN`, `PACIENTE`, `SEXO`, `NASCIMENTO`, `Nr_da_Amostra`, `Sintoma`, `Coleta`, `RES_ELISA`, `CO`, `DO`, `RES_MAT`,
`NOVA_COLETA`, `1o_SOROVAR`, `1o_TIT`, `2o_SOROVAR`, `2o_TIT`, `3o_SOROVAR`, `3o_TIT`, `4o_SOROVAR`, `4o_TIT`, `5o_SOROVAR`, `5o_TIT`, `6o_SOROVAR`, `6o_TIT`, `7o_SOROVAR`, `7o_TIT`,
 `8o_SOROVAR`, `8o_TIT`, `9o_SOROVAR`, `9o_TIT`, `10o_SOROVAR`, `10o_TIT`, `11o_SOROVAR`, `11o_TIT`, `12o_SOROVAR`, `12o_TIT`, `13_SOROVAR`, `13_TIT`, `14o_SOROVAR`, `14o_TIT`,
  `15o_SOROVAR`, `15o_TIT`, `16o_SOROVAR`, `16o_TIT`, `17o_SOROVAR`, `17o_TIT`, `18o_SOROVAR`, `18o_TIT`, `19o_SOROVAR`, `19o_TIT`, `LIBERACAO_EM`, `OBSERVACAO`);


-- J11n3ts1n@n	J11	COVID (ESUS)
-- A920n3ts1n@n	A920	CHIKUNGUNYA
-- A379n3ts1n@n	A379	COQUELUCHE
-- B09n3ts1n@n	B09	DOENCAS EXANTEMATICAS
-- A959n3ts1n@n	A959	FEBRE AMARELA
-- A279n3ts1n@n	A279	LEPTOSPIROSE
--


-- Exportando novos casos do  do ccz dengue
-- LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/sv2_sivep.csv'
-- INTO TABLE `sv2david`
-- CHARACTER SET latin1
-- FIELDS TERMINATED BY ';'
-- IGNORE 1 ROWS
-- (`id`, `sinan`, `datanot`, `agravo`, `nome`, `idade`, `sexo`, `dataentrada`, `se`, `data1sint`, `localate`, `tel`, `num`, `comp`, `da`, `cep`, `log`, `rua`,
-- `bairro`, `localvd`, `suvis`, `cidade`, `idrua`, `dataobito`, `criado`, `latsv2`, `longsv2`, `usuariocad`, `alterado`, `usuarioalt`, `ocorrencia`, `tipo`);



-- LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/ruas_jacana_cep_sivep.csv'
-- INTO TABLE `ruas_jacana_cep_sivep`
-- CHARACTER SET latin1
-- FIELDS TERMINATED BY ';'
-- IGNORE 1 ROWS
-- (`ID`, `DA`, `SETOR`, `LOG`, `ENDEREÇO`, `BAIRRO`, `CEP`, `PGUIA`, `UBS`, `LAT`, `LONG`, `se`, `dataentrada`)

-- SELECT SV2.id, "0000000" AS sinan, sivep.DT_NOTIFIC AS datanot, "COVID-19" AS agravo, sivep.NM_PACIENT AS nome, Int(DateDiff("d",[DT_NASC],Date())/365.25) & "A" AS idade, sivep.CS_SEXO AS sexo, Date() AS dataentrada, (SELECT se FROM ruas_jacana_cep_sivep WHERE dataentrada = Date()) AS se, "" AS data1sint, sivep.ID_UNIDADE AS localate, "(" & [NU_DDD_TEL] & ")" & [NU_TELEFON] AS tel, sivep.NU_NUMERO AS num, sivep.NM_COMPLEM AS [comp], ruas_jacana_cep_sivep.DA AS da, Left([ruas_jacana_cep_sivep.CEP],5) & "-"+Mid([ruas_jacana_cep_sivep.CEP],6) AS cep, ruas_jacana_cep_sivep.LOG AS log, ruas_jacana_cep_sivep.ENDEREÇO AS rua, ruas_jacana_cep_sivep.BAIRRO AS bairro, ruas_jacana_cep_sivep.UBS AS localvd, "UVIS JACANA" AS suvis, "SAO PAULO" AS cidade, ruas_jacana_cep_sivep.ID AS idrua, "" AS dataobito, "" AS criado, ruas_jacana_cep_sivep.LAT AS latsv2, ruas_jacana_cep_sivep.LONG AS longsv2, "sisdamweb D790072" AS usuariocad, "" AS alterado, sivep.DT_NASC AS usuarioalt, SV2.nome AS ocorrencia, "suvis" AS tipo
-- FROM (sivep INNER JOIN ruas_jacana_cep_sivep ON sivep.NU_CEP = ruas_jacana_cep_sivep.CEP) LEFT JOIN SV2 ON sivep.NM_PACIENT = SV2.nome
-- WHERE (((SV2.nome) Is Null) AND ((ruas_jacana_cep_sivep.CEP) In (SELECT[CEP]FROM [ruas_jacana_cep_sivep] As Tmp GROUP BY [CEP] HAVING Count(*)=1)));

-- Exportando novos casos do  do ccz dengue
-- LOAD DATA LOCAL INFILE 'c:/Ambiental/csv/sivep.csv'
-- INTO TABLE `sivep`
-- CHARACTER SET latin1
-- FIELDS TERMINATED BY ';'
-- IGNORE 1 ROWS
-- (`NU_NOTIFIC`, `DT_NOTIFIC`, `SEM_NOT`, `DT_SIN_PRI`, `SEM_PRI`, `SG_UF_NOT`, `ID_REGIONA`, `CO_REGIONA`, `ID_MUNICIP`, `CO_MUN_NOT`, `ID_UNIDADE`, `CO_UNI_NOT`, `NU_CPF`, `NM_PACIENT`, `CS_SEXO`, `DT_NASC`, `NU_IDADE_N`, `TP_IDADE`, `COD_IDADE`, `CS_GESTANT`, `CS_RACA`, `CS_ETINIA`, `CS_ESCOL_N`, `NM_MAE_PAC`, `NU_CEP`, `ID_PAIS`, `CO_PAIS`, `SG_UF`, `ID_RG_RESI`, `CO_RG_RESI`, `ID_MN_RESI`, `CO_MUN_RES`, `NM_BAIRRO`, `NM_LOGRADO`, `NU_NUMERO`, `NM_COMPLEM`, `NU_DDD_TEL`, `NU_TELEFON`, `CS_ZONA`, `SURTO_SG`, `NOSOCOMIAL`, `AVE_SUINO`, `FEBRE`, `TOSSE`, `GARGANTA`, `DISPNEIA`, `DESC_RESP`, `SATURACAO`, `DIARREIA`, `VOMITO`, `OUTRO_SIN`, `OUTRO_DES`, `PUERPERA`, `CARDIOPATI`, `HEMATOLOGI`, `SIND_DOWN`, `HEPATICA`, `ASMA`, `DIABETES`, `NEUROLOGIC`, `PNEUMOPATI`, `IMUNODEPRE`, `RENAL`, `OBESIDADE`, `OBES_IMC`, `OUT_MORBI`, `MORB_DESC`, `VACINA`, `DT_UT_DOSE`, `MAE_VAC`, `DT_VAC_MAE`, `M_AMAMENTA`, `DT_DOSEUNI`, `DT_1_DOSE`, `DT_2_DOSE`, `ANTIVIRAL`, `TP_ANTIVIR`, `OUT_ANTIV`, `DT_ANTIVIR`, `HOSPITAL`, `DT_INTERNA`, `SG_UF_INTE`, `ID_RG_INTE`, `CO_RG_INTE`, `ID_MN_INTE`, `CO_MU_INTE`, `NM_UN_INTE`, `CO_UN_INTE`, `UTI`, `DT_ENTUTI`, `DT_SAIDUTI`, `SUPORT_VEN`, `RAIOX_RES`, `RAIOX_OUT`, `DT_RAIOX`, `AMOSTRA`, `DT_COLETA`, `TP_AMOSTRA`, `OUT_AMOST`, `REQUI_GAL`, `IF_RESUL`, `DT_IF`, `POS_IF_FLU`, `TP_FLU_IF`, `POS_IF_OUT`, `IF_VSR`, `IF_PARA1`, `IF_PARA2`, `IF_PARA3`, `IF_ADENO`, `IF_OUTRO`, `DS_IF_OUT`, `LAB_IF`, `CO_LAB_IF`, `PCR_RESUL`, `DT_PCR`, `POS_PCRFLU`, `TP_FLU_PCR`, `PCR_FLUASU`, `FLUASU_OUT`, `PCR_FLUBLI`, `FLUBLI_OUT`, `POS_PCROUT`, `PCR_VSR`, `PCR_PARA1`, `PCR_PARA2`, `PCR_PARA3`, `PCR_PARA4`, `PCR_ADENO`, `PCR_METAP`, `PCR_BOCA`, `PCR_RINO`, `PCR_OUTRO`, `DS_PCR_OUT`, `LAB_PCR`, `CO_LAB_PCR`, `CLASSI_FIN`, `CLASSI_OUT`, `CRITERIO`, `EVOLUCAO`, `DT_EVOLUCA`, `DT_ENCERRA`, `OBSERVA`, `NOME_PROF`, `REG_PROF`, `DT_DIGITA`, `HISTO_VGM`, `PAIS_VGM`, `CO_PS_VGM`, `LO_PS_VGM`, `DT_VGM`, `DT_RT_VGM`, `PCR_SARS2`, `PAC_COCBO`, `PAC_DSCBO`)
